// components/Settings/Filter/FilterLinksSettings.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useGuildSettings } from '~/composables/settings/useGuildSettings';
import { useGuildSettingsChanges } from '~/composables/settings/useGuildSettingsChanges';

import { bitwiseHas, bitwiseSet, updateSliderValueObj } from '~/utils/util';

const { guildSettings } = useGuildSettings();
const { setGuildSettingsChanges } = useGuildSettingsChanges();

const newWord = ref('');

const softActionEnabled = computed(() => ({
	alerts: bitwiseHas(guildSettings.value.selfmodLinksSoftAction, 0b100),
	logs: bitwiseHas(guildSettings.value.selfmodLinksSoftAction, 0b010),
	deletes: bitwiseHas(guildSettings.value.selfmodLinksSoftAction, 0b001)
}));

const updateSoftAction = (bit: number, checked: boolean) => {
	setGuildSettingsChanges({
		selfmodLinksSoftAction: bitwiseSet(guildSettings.value.selfmodLinksSoftAction, bit, checked)
	});
};

const addLink = () => {
	try {
		const { hostname } = new URL(/^https?:\/\//.test(newWord.value) ? newWord.value : `https://${newWord.value}`);
		if (hostname.length <= 128 && !guildSettings.value.selfmodLinksAllowed.includes(hostname)) {
			setGuildSettingsChanges({
				selfmodLinksAllowed: [...guildSettings.value.selfmodLinksAllowed, hostname]
			});
			newWord.value = '';
		}
	} catch {
		// intentionally empty
	}
};

const removeLink = (word: string) => {
	setGuildSettingsChanges({
		selfmodLinksAllowed: guildSettings.value.selfmodLinksAllowed.filter((item) => item !== word)
	});
};
</script>

<template>
	<div>
		<PresentationalLayoutsSettingsSection title="Link Filter">
			<div class="grid grid-cols-1 gap-4 md:grid-cols-2">
				<SelectsSelectBoolean
					:title="`Filter ${guildSettings.selfmodLinksEnabled ? 'Enabled' : 'Disabled'}`"
					:current-value="guildSettings.selfmodLinksEnabled"
					description="Whether or not this system should be enabled."
					@change="(value) => setGuildSettingsChanges({ selfmodLinksEnabled: value })"
				/>
				<SelectsSelectBoolean
					:title="`Alerts ${softActionEnabled.alerts ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.alerts"
					description="Toggle message alerts in the channel the infraction took place."
					@change="(value) => updateSoftAction(0b100, value)"
				/>
				<SelectsSelectBoolean
					:title="`Logs ${softActionEnabled.logs ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.logs"
					description="Toggle message logs in the moderation logs channel."
					@change="(value) => updateSoftAction(0b010, value)"
				/>
				<SelectsSelectBoolean
					:title="`Deletes ${softActionEnabled.deletes ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.deletes"
					description="Toggle message deletions."
					@change="(value) => updateSoftAction(0b001, value)"
				/>
			</div>
		</PresentationalLayoutsSettingsSection>

		<PresentationalLayoutsSettingsSection title="Punishments">
			<div class="flex flex-col gap-4 md:flex-row">
				<SelectsSelect
					title="Action"
					helper-text="The action to perform as punishment"
					:value="guildSettings.selfmodLinksHardAction"
					@change="(value) => value && setGuildSettingsChanges({ selfmodLinksHardAction: typeof value === 'string' ? +value : value })"
				>
					<option :value="0">None</option>
					<option :value="1">Warning</option>
					<option :value="2">Kick</option>
					<option :value="3">Mute</option>
					<option :value="4">Softban</option>
					<option :value="5">Ban</option>
				</SelectsSelect>
				<SelectsSelectDuration
					:value="guildSettings.selfmodLinksHardActionDuration"
					:min="1000"
					@change="(duration) => setGuildSettingsChanges({ selfmodLinksHardActionDuration: duration })"
				/>
			</div>

			<div class="mt-4">
				<p>Maximum Threshold</p>
				<input
					type="range"
					min="0"
					max="60"
					:value="guildSettings.selfmodLinksThresholdMaximum"
					@input="
						(e) =>
							setGuildSettingsChanges(
								updateSliderValueObj('selfmodLinksThresholdMaximum', Number((e.target as HTMLInputElement).value))
							)
					"
					class="range"
				/>
			</div>

			<div class="mt-4">
				<p>Threshold Duration (in seconds)</p>
				<input
					type="range"
					min="0"
					max="120"
					:value="guildSettings.selfmodLinksThresholdDuration / 1000"
					@input="
						(e) =>
							setGuildSettingsChanges(
								updateSliderValueObj('selfmodLinksThresholdDuration', Number((e.target as HTMLInputElement).value) * 1000)
							)
					"
					class="range"
				/>
			</div>
		</PresentationalLayoutsSettingsSection>

		<PresentationalLayoutsSettingsSection title="Options">
			<form @submit.prevent="addLink" class="mb-4 flex items-center">
				<input v-model="newWord" type="text" placeholder="Add Link" class="input input-bordered mr-2" />
				<button type="submit" class="btn btn-primary">Confirm</button>
			</form>

			<div v-if="guildSettings.selfmodLinksAllowed.length > 0" class="flex flex-wrap gap-2">
				<div v-for="word in guildSettings.selfmodLinksAllowed" :key="word" class="badge badge-primary badge-lg">
					{{ word }}
					<button class="btn btn-ghost btn-xs" @click="removeLink(word)">×</button>
				</div>
			</div>
		</PresentationalLayoutsSettingsSection>
	</div>
</template>

// src/components/pages/Settings/Filter/FilterLinksSettings.tsx
import { useGuildSettingsChangesContext } from '@contexts/Settings/GuildSettingsChangesContext';
import { useGuildSettingsContext } from '@contexts/Settings/GuildSettingsContext';
import Section from '@layout/Settings/Section';
import SimpleGrid from '@material/SimpleGrid';
import Select from '@selects/Select';
import SelectBoolean from '@selects/SelectBoolean';
import SelectDuration from '@selects/SelectDuration';
import { bitwiseHas, bitwiseSet, updateSliderValueObj } from '@utils/util';
import { Fragment, memo, useState, type FC } from 'react';

import { Box, Button, Chip, MenuItem, Paper, Slider, TextField, Typography } from '@mui/material';

const FilterLinksSettings: FC = () => {
	const [newWord, setNewWord] = useState('');
	const { guildSettings } = useGuildSettingsContext();
	const { setGuildSettingsChanges } = useGuildSettingsChangesContext();

	return (
		<Fragment>
			<Section title="Link Filter">
				<SimpleGrid>
					<SelectBoolean
						title={`Filter ${guildSettings.selfmodLinksEnabled ? 'Enabled' : 'Disabled'}`}
						onChange={(event) => setGuildSettingsChanges({ selfmodLinksEnabled: event.target.checked })}
						currentValue={guildSettings.selfmodLinksEnabled}
						description="Whether or not this system should be enabled."
					/>
					<SelectBoolean
						title={`Alerts ${bitwiseHas(guildSettings.selfmodLinksSoftAction, 0b100) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodLinksSoftAction: bitwiseSet(guildSettings.selfmodLinksSoftAction, 0b100, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodLinksSoftAction, 0b100)}
						description="Toggle message alerts in the channel the infraction took place."
					/>
					<SelectBoolean
						title={`Logs ${bitwiseHas(guildSettings.selfmodLinksSoftAction, 0b010) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodLinksSoftAction: bitwiseSet(guildSettings.selfmodLinksSoftAction, 0b010, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodLinksSoftAction, 0b010)}
						description="Toggle message logs in the moderation logs channel."
					/>
					<SelectBoolean
						title={`Deletes ${bitwiseHas(guildSettings.selfmodLinksSoftAction, 0b001) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodLinksSoftAction: bitwiseSet(guildSettings.selfmodLinksSoftAction, 0b001, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodLinksSoftAction, 0b001)}
						description="Toggle message deletions."
					/>
				</SimpleGrid>
			</Section>
			<Section title="Punishments">
				<SimpleGrid direction="row" justifyContent="flex-start">
					<Select
						title="Action"
						helperText="The action to perform as punishment"
						value={guildSettings.selfmodLinksHardAction}
						onChange={(e) => setGuildSettingsChanges({ selfmodLinksHardAction: e.target.value })}
					>
						<MenuItem value={0}>None</MenuItem>
						<MenuItem value={1}>Warning</MenuItem>
						<MenuItem value={2}>Kick</MenuItem>
						<MenuItem value={3}>Mute</MenuItem>
						<MenuItem value={4}>Softban</MenuItem>
						<MenuItem value={5}>Ban</MenuItem>
					</Select>
					<SelectDuration
						value={guildSettings.selfmodLinksHardActionDuration}
						min={1000}
						onChange={(duration) => setGuildSettingsChanges({ selfmodLinksHardActionDuration: duration })}
					></SelectDuration>
				</SimpleGrid>
				<Typography>Maximum Threshold</Typography>
				<Slider
					value={guildSettings.selfmodLinksThresholdMaximum}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('selfmodLinksThresholdMaximum', value))}
					aria-labelledby="Links selfmod filter maximum threshold slider"
					valueLabelDisplay="auto"
					min={0}
					max={60}
				/>
				<Typography>Threshold Duration (in seconds)</Typography>
				<Slider
					value={guildSettings.selfmodLinksThresholdDuration / 1000}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('selfmodLinksThresholdDuration', value, 1000))}
					aria-labelledby="Links selfmod filter threshold duration slider"
					valueLabelDisplay="auto"
					min={0}
					max={120}
				/>
			</Section>
			<Section title="Options">
				<form
					onSubmit={(e) => {
						e.preventDefault();
						try {
							const { hostname } = new URL(/^https?:\/\//.test(newWord) ? newWord : `https://${newWord}`);
							if (hostname.length <= 128 && !guildSettings.selfmodLinksAllowed.includes(hostname)) {
								setGuildSettingsChanges({
									selfmodLinksAllowed: [...guildSettings.selfmodLinksAllowed, hostname]
								});
								setNewWord('');
							}
						} catch {
							// intentionally empty
						}
					}}
				>
					<Box display="flex" mb={2} alignContent="center" alignItems="center" justifyContent="flex-start">
						<TextField
							sx={{
								mr: 1,
								mb: 1
							}}
							label="Add Link"
							value={newWord}
							onChange={(e) => setNewWord(e.target.value)}
						/>
						<Button type="submit" variant="contained" color="primary">
							Confirm
						</Button>
					</Box>
				</form>

				{guildSettings.selfmodLinksAllowed.length !== 0 && (
					<Paper
						sx={{
							p: 1,
							'& > *': {
								m: 1
							}
						}}
					>
						{guildSettings.selfmodLinksAllowed.map((word) => (
							<Chip
								color="primary"
								key={word}
								label={word}
								onDelete={() =>
									setGuildSettingsChanges({
										selfmodLinksAllowed: guildSettings.selfmodLinksAllowed.filter((item) => item !== word)
									})
								}
							/>
						))}
					</Paper>
				)}
			</Section>
		</Fragment>
	);
};

export default memo(FilterLinksSettings);
