// components/pages/Settings/Filter/FilterMessagesSettings.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useGuildSettingsChanges } from '~/composables/settings/useGuildSettingsChanges';
import { useGuildSettings } from '~/composables/settings/useGuildSettings';
import Section from '~/layouts/settings/section.vue';
import SelectBoolean from '~/components/selects/SelectBoolean.vue';
import Select from '~/components/selects/Select.vue';
import SelectDuration from '~/components/selects/SelectDuration.vue';
import { bitwiseHas, bitwiseSet, updateSliderValueObj } from '~/utils/util';

const { guildSettings } = useGuildSettings();
const { setGuildSettingsChanges } = useGuildSettingsChanges();

const softActionEnabled = computed(() => ({
	alerts: bitwiseHas(guildSettings.value.selfmodMessagesSoftAction, 0b100),
	logs: bitwiseHas(guildSettings.value.selfmodMessagesSoftAction, 0b010),
	deletes: bitwiseHas(guildSettings.value.selfmodMessagesSoftAction, 0b001)
}));

const updateSoftAction = (bit: number, checked: boolean) => {
	setGuildSettingsChanges({
		selfmodMessagesSoftAction: bitwiseSet(guildSettings.value.selfmodMessagesSoftAction, bit, checked)
	});
};
</script>

<template>
	<div>
		<Section title="Message Duplication Filter">
			<div class="grid grid-cols-1 gap-4 md:grid-cols-2">
				<SelectBoolean
					:title="`Filter ${guildSettings.selfmodMessagesEnabled ? 'Enabled' : 'Disabled'}`"
					:current-value="guildSettings.selfmodMessagesEnabled"
					description="Whether or not this system should be enabled."
					@change="(value) => setGuildSettingsChanges({ selfmodMessagesEnabled: value })"
				/>
				<SelectBoolean
					:title="`Alerts ${softActionEnabled.alerts ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.alerts"
					description="Toggle message alerts in the channel the infraction took place."
					@change="(value) => updateSoftAction(0b100, value)"
				/>
				<SelectBoolean
					:title="`Logs ${softActionEnabled.logs ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.logs"
					description="Toggle message logs in the moderation logs channel."
					@change="(value) => updateSoftAction(0b010, value)"
				/>
				<SelectBoolean
					:title="`Deletes ${softActionEnabled.deletes ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.deletes"
					description="Toggle message deletions."
					@change="(value) => updateSoftAction(0b001, value)"
				/>
			</div>
		</Section>

		<Section title="Punishments">
			<div class="flex flex-col gap-4 md:flex-row">
				<Select
					title="Action"
					helper-text="The action to perform as punishment"
					:value="guildSettings.selfmodMessagesHardAction"
					@change="(value) => setGuildSettingsChanges({ selfmodMessagesHardAction: Number(value) })"
				>
					<option :value="0">None</option>
					<option :value="1">Warning</option>
					<option :value="2">Kick</option>
					<option :value="3">Mute</option>
					<option :value="4">Softban</option>
					<option :value="5">Ban</option>
				</Select>
				<SelectDuration
					:value="guildSettings.selfmodMessagesHardActionDuration"
					:min="1000"
					@change="
						(duration) =>
							setGuildSettingsChanges({ selfmodMessagesHardActionDuration: typeof duration === 'string' ? +duration : duration })
					"
				/>
			</div>

			<div class="mt-4">
				<p>Maximum Threshold</p>
				<input
					type="range"
					min="0"
					max="60"
					:value="guildSettings.selfmodMessagesThresholdMaximum"
					@input="
						(e) =>
							setGuildSettingsChanges(
								updateSliderValueObj('selfmodMessagesThresholdMaximum', Number((e.target as HTMLInputElement)?.value))
							)
					"
					class="range"
				/>
			</div>

			<div class="mt-4">
				<p>Threshold Duration (in seconds)</p>
				<input
					type="range"
					min="0"
					max="120"
					:value="guildSettings.selfmodMessagesThresholdDuration / 1000"
					@input="
						(e) =>
							setGuildSettingsChanges(
								updateSliderValueObj('selfmodMessagesThresholdDuration', Number((e.target as HTMLInputElement)?.value) * 1000)
							)
					"
					class="range"
				/>
			</div>
		</Section>
	</div>
</template>

// src/components/pages/Settings/Filter/FilterMessagesSettings.tsx
import { useGuildSettingsChangesContext } from '@contexts/Settings/GuildSettingsChangesContext';
import { useGuildSettingsContext } from '@contexts/Settings/GuildSettingsContext';
import Section from '@layout/Settings/Section';
import SimpleGrid from '@material/SimpleGrid';
import Select from '@selects/Select';
import SelectBoolean from '@selects/SelectBoolean';
import SelectDuration from '@selects/SelectDuration';
import { bitwiseHas, bitwiseSet, updateSliderValueObj } from '@utils/util';
import { Fragment, memo, type FC } from 'react';

import { MenuItem, Slider, Typography } from '@mui/material';

const FilterMessagesSettings: FC = () => {
	const { guildSettings } = useGuildSettingsContext();
	const { setGuildSettingsChanges } = useGuildSettingsChangesContext();

	return (
		<Fragment>
			<Section title="Message Duplication Filter">
				<SimpleGrid>
					<SelectBoolean
						title={`Filter ${guildSettings.selfmodMessagesEnabled ? 'Enabled' : 'Disabled'}`}
						onChange={(event) => setGuildSettingsChanges({ selfmodMessagesEnabled: event.target.checked })}
						currentValue={guildSettings.selfmodMessagesEnabled}
						description="Whether or not this system should be enabled."
					/>
					<SelectBoolean
						title={`Alerts ${bitwiseHas(guildSettings.selfmodMessagesSoftAction, 0b100) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodMessagesSoftAction: bitwiseSet(guildSettings.selfmodMessagesSoftAction, 0b100, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodMessagesSoftAction, 0b100)}
						description="Toggle message alerts in the channel the infraction took place."
					/>
					<SelectBoolean
						title={`Logs ${bitwiseHas(guildSettings.selfmodMessagesSoftAction, 0b010) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodMessagesSoftAction: bitwiseSet(guildSettings.selfmodMessagesSoftAction, 0b010, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodMessagesSoftAction, 0b010)}
						description="Toggle message logs in the moderation logs channel."
					/>
					<SelectBoolean
						title={`Deletes ${bitwiseHas(guildSettings.selfmodMessagesSoftAction, 0b001) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodMessagesSoftAction: bitwiseSet(guildSettings.selfmodMessagesSoftAction, 0b001, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodMessagesSoftAction, 0b001)}
						description="Toggle message deletions."
					/>
				</SimpleGrid>
			</Section>
			<Section title="Punishments">
				<SimpleGrid direction="row" justifyContent="flex-start">
					<Select
						title="Action"
						helperText="The action to perform as punishment"
						value={guildSettings.selfmodMessagesHardAction}
						onChange={(e) => setGuildSettingsChanges({ selfmodMessagesHardAction: e.target.value })}
					>
						<MenuItem value={0}>None</MenuItem>
						<MenuItem value={1}>Warning</MenuItem>
						<MenuItem value={2}>Kick</MenuItem>
						<MenuItem value={3}>Mute</MenuItem>
						<MenuItem value={4}>Softban</MenuItem>
						<MenuItem value={5}>Ban</MenuItem>
					</Select>
					<SelectDuration
						value={guildSettings.selfmodMessagesHardActionDuration}
						min={1000}
						onChange={(duration) => setGuildSettingsChanges({ selfmodMessagesHardActionDuration: duration })}
					></SelectDuration>
				</SimpleGrid>
				<Typography>Maximum Threshold</Typography>
				<Slider
					value={guildSettings.selfmodMessagesThresholdMaximum}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('selfmodMessagesThresholdMaximum', value))}
					aria-labelledby="Messages selfmod filter maximum threshold slider"
					valueLabelDisplay="auto"
					min={0}
					max={60}
				/>
				<Typography>Threshold Duration (in seconds)</Typography>
				<Slider
					value={guildSettings.selfmodMessagesThresholdDuration / 1000}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('selfmodMessagesThresholdDuration', value, 1000))}
					aria-labelledby="Messages selfmod filter threshold duration slider"
					valueLabelDisplay="auto"
					min={0}
					max={120}
				/>
			</Section>
		</Fragment>
	);
};

export default memo(FilterMessagesSettings);
