// components/Settings/Filter/FilterInvitesSettings.vue
<script setup lang="ts">
import { useGuildSettingsChanges } from '~/composables/settings/useGuildSettingsChanges';
import { useGuildSettings } from '~/composables/settings/useGuildSettings';

const { guildSettings } = useGuildSettings();

const { setGuildSettingsChanges } = useGuildSettingsChanges();

const softActionEnabled = computed(() => ({
	alerts: bitwiseHas(guildSettings.value.selfmodNewlinesSoftAction, 0b100),
	logs: bitwiseHas(guildSettings.value.selfmodNewlinesSoftAction, 0b010),
	deletes: bitwiseHas(guildSettings.value.selfmodNewlinesSoftAction, 0b001)
}));

const updateSoftAction = (bit: number, checked: boolean) => {
	setGuildSettingsChanges({
		selfmodNewlinesSoftAction: bitwiseSet(guildSettings.value.selfmodNewlinesSoftAction, bit, checked)
	});
};
</script>

<template>
	<div>
		<PresentationalLayoutsSettingsSection title="Line Spam Filter">
			<div class="grid grid-cols-1 gap-4 md:grid-cols-2">
				<SelectsSelectBoolean
					:title="`Filter ${guildSettings.selfmodNewlinesEnabled ? 'Enabled' : 'Disabled'}`"
					:current-value="guildSettings.selfmodNewlinesEnabled"
					description="Whether or not this system should be enabled."
					@change="(value) => setGuildSettingsChanges({ selfmodNewlinesEnabled: value })"
				/>
				<SelectsSelectBoolean
					:title="`Alerts ${softActionEnabled.alerts ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.alerts"
					description="Toggle message alerts in the channel the infraction took place."
					@change="(value) => updateSoftAction(0b100, value)"
				/>
				<SelectsSelectBoolean
					:title="`Logs ${softActionEnabled.logs ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.logs"
					description="Toggle message logs in the moderation logs channel."
					@change="(value) => updateSoftAction(0b010, value)"
				/>
				<SelectsSelectBoolean
					:title="`Deletes ${softActionEnabled.deletes ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.deletes"
					description="Toggle message deletions."
					@change="(value) => updateSoftAction(0b001, value)"
				/>
			</div>
		</PresentationalLayoutsSettingsSection>

		<PresentationalLayoutsSettingsSection title="Punishments">
			<div class="flex flex-col gap-4 md:flex-row">
				<SelectsSelect
					title="Action"
					helper-text="The action to perform as punishment"
					:value="guildSettings.selfmodNewlinesHardAction"
					@change="(value) => value && setGuildSettingsChanges({ selfmodNewlinesHardAction: typeof value === 'string' ? +value : value })"
				>
					<option :value="0">None</option>
					<option :value="1">Warning</option>
					<option :value="2">Kick</option>
					<option :value="3">Mute</option>
					<option :value="4">Softban</option>
					<option :value="5">Ban</option>
				</SelectsSelect>
				<SelectsSelectDuration
					:value="guildSettings.selfmodNewlinesHardActionDuration"
					:min="1000"
					@change="(duration) => setGuildSettingsChanges({ selfmodNewlinesHardActionDuration: duration })"
				/>
			</div>

			<div class="mt-4">
				<p>Maximum Threshold</p>
				<input
					type="range"
					min="0"
					max="60"
					:value="guildSettings.selfmodNewlinesThresholdMaximum"
					class="range"
					@input="
						(e) =>
							setGuildSettingsChanges(
								updateSliderValueObj('selfmodNewlinesThresholdMaximum', Number((e.target as HTMLInputElement)?.value))
							)
					"
				/>
			</div>

			<div class="mt-4">
				<p>Threshold Duration (in seconds)</p>
				<input
					type="range"
					min="0"
					max="120"
					:value="guildSettings.selfmodNewlinesThresholdDuration / 1000"
					class="range"
					@input="
						(e) =>
							setGuildSettingsChanges(
								updateSliderValueObj('selfmodNewlinesThresholdDuration', Number((e.target as HTMLInputElement)?.value) * 1000)
							)
					"
				/>
			</div>
		</PresentationalLayoutsSettingsSection>

		<PresentationalLayoutsSettingsSection title="Options">
			<div class="mt-4">
				<p>Maximum amount of new lines in a message before filter is applied</p>
				<input
					type="range"
					min="10"
					max="2000"
					:value="guildSettings.selfmodNewlinesMaximum"
					class="range"
					@input="
						(e) => setGuildSettingsChanges(updateSliderValueObj('selfmodNewlinesMaximum', Number((e.target as HTMLInputElement)?.value)))
					"
				/>
			</div>
		</PresentationalLayoutsSettingsSection>
	</div>
</template>

// src/components/pages/Settings/Filter/FilterInvitesSettings.tsx
import { useGuildSettingsChangesContext } from '@contexts/Settings/GuildSettingsChangesContext';
import { useGuildSettingsContext } from '@contexts/Settings/GuildSettingsContext';
import Section from '@layout/Settings/Section';
import MenuItem from '@mui/material/MenuItem';
import Slider from '@mui/material/Slider';
import Typography from '@mui/material/Typography';
import SimpleGrid from '@mui/SimpleGrid';
import Select from '@selects/Select';
import SelectBoolean from '@selects/SelectBoolean';
import SelectDuration from '@selects/SelectDuration';
import { bitwiseHas, bitwiseSet, updateSliderValueObj } from '@utils/util';
import React, { FC, Fragment, memo } from 'react';

const FilterInvitesSettings: FC = () => {
	const { guildSettings } = useGuildSettingsContext();
	const { setGuildSettingsChanges } = useGuildSettingsChangesContext();

	return (
		<Fragment>
			<Section title="Invite Link Filter">
				<SimpleGrid>
					<SelectBoolean
						title={`Filter ${guildSettings.selfmodInvitesEnabled ? 'Enabled' : 'Disabled'}`}
						onChange={(event) => setGuildSettingsChanges({ selfmodInvitesEnabled: event.target.checked })}
						currentValue={guildSettings.selfmodInvitesEnabled}
						description="Whether or not this system should be enabled."
					/>
					<SelectBoolean
						title={`Alerts ${bitwiseHas(guildSettings.selfmodInvitesSoftAction, 0b100) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodInvitesSoftAction: bitwiseSet(guildSettings.selfmodInvitesSoftAction, 0b100, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodInvitesSoftAction, 0b100)}
						description="Toggle message alerts in the channel the infraction took place."
					/>
					<SelectBoolean
						title={`Logs ${bitwiseHas(guildSettings.selfmodInvitesSoftAction, 0b010) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodInvitesSoftAction: bitwiseSet(guildSettings.selfmodInvitesSoftAction, 0b010, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodInvitesSoftAction, 0b010)}
						description="Toggle message logs in the moderation logs channel."
					/>
					<SelectBoolean
						title={`Deletes ${bitwiseHas(guildSettings.selfmodInvitesSoftAction, 0b001) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodInvitesSoftAction: bitwiseSet(guildSettings.selfmodInvitesSoftAction, 0b001, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodInvitesSoftAction, 0b001)}
						description="Toggle message deletions."
					/>
				</SimpleGrid>
			</Section>
			<Section title="Punishments">
				<SimpleGrid direction="row" justifyContent="flex-start">
					<Select
						title="Action"
						helperText="The action to perform as punishment"
						value={guildSettings.selfmodInvitesHardAction}
						onChange={(e) => setGuildSettingsChanges({ selfmodInvitesHardAction: e.target.value })}
					>
						<MenuItem value={0}>None</MenuItem>
						<MenuItem value={1}>Warning</MenuItem>
						<MenuItem value={2}>Kick</MenuItem>
						<MenuItem value={3}>Mute</MenuItem>
						<MenuItem value={4}>Softban</MenuItem>
						<MenuItem value={5}>Ban</MenuItem>
					</Select>
					<SelectDuration
						value={guildSettings.selfmodInvitesHardActionDuration}
						min={1000}
						onChange={(duration) => setGuildSettingsChanges({ selfmodInvitesHardActionDuration: duration })}
					></SelectDuration>
				</SimpleGrid>
				<Typography>Maximum Threshold</Typography>
				<Slider
					value={guildSettings.selfmodInvitesThresholdMaximum}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('selfmodInvitesThresholdMaximum', value))}
					aria-labelledby="Invites selfmod filter maximum threshold slider"
					valueLabelDisplay="auto"
					min={0}
					max={60}
				/>
				<Typography>Threshold Duration (in seconds)</Typography>
				<Slider
					value={guildSettings.selfmodInvitesThresholdDuration / 1000}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('selfmodInvitesThresholdDuration', value, 1000))}
					aria-labelledby="Invites selfmod filter threshold duration slider"
					valueLabelDisplay="auto"
					min={0}
					max={120}
				/>
			</Section>
		</Fragment>
	);
};

export default memo(FilterInvitesSettings);
