// src/components/RedirectRoute.tsx
import React from 'react';
import { Route, RouteProps } from 'react-router-dom';

export interface RedirectRouteProps extends RouteProps {
	redirectUri: string;
	path: string;
}

const RedirectRoute = ({ redirectUri, ...rest }: RedirectRouteProps) => (
	<Route
		{...rest}
		component={() => {
			window.location.replace(redirectUri);
			return null;
		}}
	/>
);

export default RedirectRoute;

// components/pages/routing/RedirectRoute.vue
<template>
	<slot />
</template>

<script setup lang="ts">
import { onMounted, defineProps } from 'vue';

interface RedirectRouteProps {
	redirectUri: string;
}

const props = defineProps<RedirectRouteProps>();

const router = useRouter();

onMounted(() => {
	router.replace(props.redirectUri);
});
</script>
