// components/pages/routing/RedirectRoute.vue
<template>
	<slot />
</template>

<script setup lang="ts">
import { onMounted, defineProps } from 'vue';

interface RedirectRouteProps {
	redirectUri: string;
}

const props = defineProps<RedirectRouteProps>();

const router = useRouter();

onMounted(() => {
	router.replace(props.redirectUri);
});
</script>

// src/components/routing/RedirectRoute.tsx
import { useRouter } from 'next/router';
import React, { FC, useEffect } from 'react';

export interface RedirectRouteProps {
	redirectUri: string;
}

const RedirectRoute: FC<RedirectRouteProps> = ({ redirectUri, children }) => {
	const router = useRouter();

	useEffect(() => {
		router.replace(redirectUri);
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	return <>{children}</>;
};

export default RedirectRoute;
