// components/presentational/CommandsPage/Chips.vue
<template>
	<div class="chips-container">
		<div class="grid grid-cols-1 gap-2 md:grid-cols-2 lg:grid-cols-3">
			<div v-if="command.permissionLevel > 0" class="col-span-1">
				<div class="chip secondary">
					<span>
						{{ isMobile ? mobileTitles[command.permissionLevel] : titles[command.permissionLevel] }}
					</span>
					<i class="mdi mdi-arrow-expand-down" />
				</div>
			</div>
			<div v-if="isGuildOnly" class="col-span-1">
				<div class="chip secondary">
					<span>
						{{ isMobile ? 'Usable in servers only.' : 'This can only be used in servers.' }}
					</span>
					<i class="mdi mdi-discord" />
				</div>
			</div>
			<div v-if="command.guarded" class="col-span-1">
				<div class="chip secondary">
					<span>This command cannot be disabled.</span>
					<i class="mdi mdi-lock" />
				</div>
			</div>
		</div>
	</div>
</template>

<script lang="ts" setup>
import type { FlattenedCommand } from '~/config/types/ApiData';

interface CommandProps {
	command: FlattenedCommand;
}

const GuildOnlyPreconditions = ['Administrator', 'DJ', 'GuildOnly', 'Moderator', 'NewsOnly', 'NSFW', 'TextOnly'];

const props = defineProps<CommandProps>();

const titles: Record<number, string> = {
	4: 'This can only be ran by staff members.',
	5: 'This can only be ran by moderators and administrators.',
	6: 'This can only be ran by administrators.'
};

const mobileTitles: Record<number, string> = {
	4: 'Staff members only',
	5: 'Moderators & administrators only',
	6: 'Administrators only'
};

const isGuildOnly = computed(() => {
	return props.command.preconditions.entries
		.flatMap((preconditionEntry) => preconditionEntry.entries)
		.filter(Boolean)
		.map((entry) => entry.name)
		.some((predicate) => GuildOnlyPreconditions.includes(predicate));
});

const { isMobile } = useDevice();
</script>

<style scoped>
.chips-container {
	display: flex;
	flex-wrap: wrap;
	gap: 0.5rem;
}

.chip {
	display: flex;
	justify-content: space-between;
	align-items: center;
	border-radius: 0.5rem;
	background-color: var(--primary-color);
	padding: 0.5rem 1rem;
	color: white;
}

.chip.secondary {
	background-color: var(--secondary-color);
}
</style>

// src/components/presentational/CommandsPage/Chips.tsx
import type { FlattenedCommand } from '@config/types/ApiData';
import DoubleArrowIcon from '@mui/icons-material/DoubleArrow';
import LockIcon from '@mui/icons-material/Lock';
import { Chip, Grid } from '@mui/material';
import { amber, deepOrange } from '@mui/material/colors';
import { useMobileContext } from 'contexts/MobileContext';
import DiscordIcon from 'mdi-react/DiscordIcon';
import React, { FC, memo, useCallback, useMemo } from 'react';

interface ChipsProps {
	command: FlattenedCommand;
}

const GuildOnlyPreconditions = ['Administrator', 'DJ', 'GuildOnly', 'Moderator', 'NewsOnly', 'NSFW', 'TextOnly'];

const Chips: FC<ChipsProps> = ({ command }) => {
	const { isMobile } = useMobileContext();

	const titles = useMemo<Record<number, string>>(
		() => ({
			4: 'This can only be ran by staff members.',
			5: 'This can only be ran by moderators and administrators.',
			6: 'This can only be ran by administrators.'
		}),
		[]
	);

	const mobileTitles = useMemo<Record<number, string>>(
		() => ({
			4: 'Staff members only',
			5: 'Moderators & administrators only',
			6: 'Administrators only'
		}),
		[]
	);

	const isGuildOnly = useCallback(() => {
		return command.preconditions.entries
			.flatMap((preconditionEntry) => preconditionEntry.entries)
			.filter(Boolean)
			.map((entry) => entry.name)
			.some((predicate) => GuildOnlyPreconditions.includes(predicate));
	}, [command.preconditions.entries]);

	return (
		<Grid container spacing={1} direction="row" alignContent="center" alignItems="center" justifyContent="flex-start">
			{command.permissionLevel > 0 && (
				<Grid item xs={12} md={5} lg={4}>
					<Chip
						size="small"
						label={isMobile ? mobileTitles[command.permissionLevel] : titles[command.permissionLevel]}
						icon={<DoubleArrowIcon />}
						color="secondary"
						sx={{
							padding: 0.2,
							marginLeft: 1,
							width: '100%',
							'& .MuiChip-iconSmall': {
								transform: 'rotate(-90deg)',
								color: amber[500]
							}
						}}
					/>
				</Grid>
			)}
			{isGuildOnly() && (
				<Grid item xs={12} md={5} lg={4}>
					<Chip
						size="small"
						label={isMobile ? 'Usable in servers only.' : 'This can only be used in servers.'}
						icon={<DiscordIcon />}
						color="secondary"
						sx={{
							padding: 0.2,
							marginLeft: 1,
							width: '100%',
							'& .MuiChip-iconSmall': {
								color: '#7289DA'
							}
						}}
					/>
				</Grid>
			)}
			{command.guarded && (
				<Grid item xs={12} md={5} lg={4}>
					<Chip
						size="small"
						label="This command cannot be disabled."
						color="secondary"
						icon={<LockIcon />}
						sx={{
							padding: 0.2,
							marginLeft: 1,
							width: '100%',
							'& .MuiChip-iconSmall': {
								color: deepOrange[500]
							}
						}}
					/>
				</Grid>
			)}
		</Grid>
	);
};

export default memo(Chips);
