// components/presentational/CommandsPage/Command.vue
<template>
	<div :class="gridItemClass">
		<div class="bg-secondary-light collapse collapse-arrow">
			<input type="checkbox" />
			<div class="collapse-title text-xl font-medium">
				<div class="flex flex-row content-start items-center justify-start">
					<div class="w-full md:w-1/3">
						<span class="text-lg font-bold" v-html="formattedCommandName"></span>
					</div>
					<div class="w-full md:w-2/3">
						<span class="text-sm text-secondary">{{ command.description }}</span>
					</div>
				</div>
			</div>
			<div class="collapse-content">
				<div class="flex flex-col">
					<template v-if="command.extendedHelp.usages">
						<ExtendedHelpSectionHeader icon="mdi-pencil" header="Command Usage" />
						<div v-for="(usage, index) in command.extendedHelp.usages" :key="index">
							<ExtendedHelpBody :body="`\`WolfStar, ${command.name} ${usage}\``" />
						</div>
					</template>

					<template v-if="command.extendedHelp.extendedHelp">
						<ExtendedHelpSectionHeader icon="mdi-help-rhombus" header="Extended Help" />
						<ExtendedHelpBody :body="resolvedExtendedHelp!" />
					</template>

					<template v-if="command.extendedHelp.explainedUsage">
						<ExtendedHelpSectionHeader icon="mdi-code-tags" header="Explained Usage" />
						<ExtendedHelpBody :body="explainedUsage!" />
					</template>

					<template v-if="command.extendedHelp.possibleFormats">
						<ExtendedHelpSectionHeader icon="mdi-brush" header="Possible Formats" />
						<ExtendedHelpBody :body="possibleFormats!" />
					</template>

					<template v-if="command.extendedHelp.examples">
						<ExtendedHelpSectionHeader icon="mdi-lightbulb-outline" header="Examples" />
						<ExtendedHelpBody :body="examples!" />
					</template>

					<template v-if="command.extendedHelp.reminder">
						<ExtendedHelpSectionHeader icon="mdi-bell-alert" header="Reminder" />
						<ExtendedHelpBody :body="command.extendedHelp.reminder" />
					</template>
				</div>
			</div>
			<div class="p-4">
				<Chips :command="command" />
			</div>
		</div>
	</div>
</template>

<script lang="ts" setup>
import { computed, defineProps } from 'vue';
import ExtendedHelpBody from './extended-help-body.vue';
import ExtendedHelpSectionHeader from './extended-help-section-header.vue';
import Chips from './Chips.vue';
import type { FlattenedCommand } from '~/config/types/ApiData';

interface CommandProps {
	command: FlattenedCommand;
}

const props = defineProps<CommandProps>();

const gridItemClass = computed(() => ({
	'flex-1': true,
	'my-2': true,
	'min-w-full': true,
	'max-w-none': true,
	'transition-width': true,
	'duration-200': true,
	'ease-in-out': true
}));

const resolveMultilineString = (str: string | string[], multiline = false): string => {
	if (Array.isArray(str)) {
		return resolveMultilineString(str.join(multiline ? '\n' : ' '), multiline);
	}
	return str
		.split('\n')
		.map((line) => line.trim())
		.join(multiline ? '\n\n' : ' ');
};

const formattedCommandName = computed(() => {
	return `s!${props.command.name}`.replace(/(.{10})/g, '$1<wbr>');
}).value;

const resolvedExtendedHelp = computed(() => {
	if (!props.command.extendedHelp.extendedHelp) return;
	return resolveMultilineString(props.command.extendedHelp.extendedHelp, true);
}).value;

const explainedUsage = computed(() => {
	if (!props.command.extendedHelp.explainedUsage) return;
	return props.command.extendedHelp.explainedUsage.map(([arg, desc]) => `- **${arg}**: ${resolveMultilineString(desc)}`).join('\n');
}).value;

const possibleFormats = computed(() => {
	if (!props.command.extendedHelp.possibleFormats) return;
	return props.command.extendedHelp.possibleFormats.map(([type, example]) => `- **${type}**: ${example}`).join('\n');
}).value;

const examples = computed(() => {
	if (!props.command.extendedHelp.examples) return;
	return props.command.extendedHelp.examples.map((example) => `- WolfStar, ${props.command.name}${example ? ` *${example}*` : ''}`).join('\n');
}).value;
</script>

<style scoped>
.chips-container {
	display: flex;
	flex-wrap: wrap;
	gap: 0.5rem;
}

.chip {
	display: flex;
	justify-content: space-between;
	align-items: center;
	border-radius: 0.5rem;
	background-color: var(--primary-color);
	padding: 0.5rem 1rem;
	color: white;
}

.chip.secondary {
	background-color: var(--secondary-color);
}
</style>

// src/components/presentational/CommandsPage/Command.tsx
import type { FlattenedCommand } from '@config/types/ApiData';
import BrushIcon from '@mui/icons-material/BrushTwoTone';
import CodeIcon from '@mui/icons-material/CodeTwoTone';
import CreateIcon from '@mui/icons-material/CreateTwoTone';
import ExamplesIcon from '@mui/icons-material/EmojiObjects';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import Chips from '@presentational/CommandsPage/Chips';
import { reactStringReplace } from '@utils/reactStringReplace';
import ReminderIcon from 'mdi-react/BellAlertIcon';
import HelpRhombusIcon from 'mdi-react/HelpRhombusIcon';
import { memo, type FC } from 'react';
import ExtendedHelpBody from './ExtendedHelpBody';
import ExtendedHelpSectionHeader from './ExtendedHelpSectionHeader';

import { Accordion, AccordionActions, AccordionDetails, AccordionSummary, Grid, Typography } from '@mui/material';

interface CommandProps {
	command: FlattenedCommand;
}

const resolveMultilineString = (str: string | string[], multiline = false): string => {
	return Array.isArray(str)
		? resolveMultilineString(str.join(multiline ? '\n' : ' '), multiline)
		: str
				.split('\n')
				.map((line) => line.trim())
				.join(multiline ? '\n\n' : ' ');
};

const Command: FC<CommandProps> = ({ command }) => {
	return (
		<Grid
			item
			sx={{
				flex: '1 1 30%',
				minWidth: '100%',
				my: 2,
				transition: 'width 0.2s ease-in-out',
				maxWidth: {
					sm: 'inherit',
					xs: 'none'
				},
				mx: {
					sm: 'inherit',
					xs: 0
				}
			}}
		>
			<Accordion TransitionProps={{ unmountOnExit: true }} elevation={4} sx={{ bgcolor: 'secondary.light' }}>
				<AccordionSummary expandIcon={<ExpandMoreIcon />}>
					<Grid container direction="row" alignItems="center" justifyContent="flex-start" alignContent="flex-start">
						<Grid item xs={12} md={3}>
							<Typography
								sx={{
									fontSize: (theme) => theme.typography.pxToRem(20),
									fontWeight: 'bolder'
								}}
							>
								{reactStringReplace(`s!${command.name}`, /(.{10})/g, (match, index) => (
									<span key={index}>
										<wbr />
										{match}
									</span>
								))}
							</Typography>
						</Grid>
						<Grid item xs={12} md={9}>
							<Typography
								component="span"
								sx={{
									fontSize: (theme) => theme.typography.pxToRem(15),
									color: 'text.secondary'
								}}
							>
								<ExtendedHelpBody body={command.description} />
							</Typography>
						</Grid>
					</Grid>
				</AccordionSummary>
				<AccordionDetails>
					<Grid container direction="column">
						{command.extendedHelp.usages && (
							<>
								<Grid item>
									<ExtendedHelpSectionHeader icon={<CreateIcon />} header="Command Usage" />
								</Grid>
								<Grid item>
									{command.extendedHelp.usages.map((usage, key) => (
										<ExtendedHelpBody key={key} body={`\`Skyra, ${command.name} ${usage}\``} />
									))}
								</Grid>
							</>
						)}

						{command.extendedHelp.extendedHelp && (
							<>
								<Grid
									item
									sx={{
										...(Boolean(command.extendedHelp.usages) && { mt: 4 })
									}}
								>
									<ExtendedHelpSectionHeader icon={<HelpRhombusIcon />} header="Extended Help" />
								</Grid>
								<Grid item>
									<ExtendedHelpBody body={resolveMultilineString(command.extendedHelp.extendedHelp, true)} />
								</Grid>
							</>
						)}

						{command.extendedHelp.explainedUsage && (
							<>
								<Grid item sx={{ mt: 4 }}>
									<ExtendedHelpSectionHeader icon={<CodeIcon />} header="Explained Usage" />
								</Grid>
								<Grid item>
									<ExtendedHelpBody
										body={command.extendedHelp.explainedUsage
											.map(([arg, desc]) => `- **${arg}**: ${resolveMultilineString(desc)}`)
											.join('\n')}
									/>
								</Grid>
							</>
						)}

						{command.extendedHelp.possibleFormats && (
							<>
								<Grid item sx={{ mt: 4 }}>
									<ExtendedHelpSectionHeader icon={<BrushIcon />} header="Possible Formats" />
								</Grid>
								<Grid item>
									<ExtendedHelpBody
										body={command.extendedHelp.possibleFormats.map(([type, example]) => `- **${type}**: ${example}`).join('\n')}
									/>
								</Grid>
							</>
						)}

						{command.extendedHelp.examples && (
							<>
								<Grid item sx={{ mt: 4 }}>
									<ExtendedHelpSectionHeader icon={<ExamplesIcon />} header="Examples" />
								</Grid>
								<Grid item>
									<ExtendedHelpBody
										body={command.extendedHelp.examples
											.map((example) => `- Skyra, ${command.name}${example ? ` *${example}*` : ''}`)
											.join('\n')}
									/>
								</Grid>
							</>
						)}

						{command.extendedHelp.reminder && (
							<>
								<Grid item sx={{ mt: 4 }}>
									<ExtendedHelpSectionHeader icon={<ReminderIcon />} header="Reminder" />
								</Grid>
								<Grid item>
									<ExtendedHelpBody body={command.extendedHelp.reminder} />
								</Grid>
							</>
						)}
					</Grid>
				</AccordionDetails>
				<AccordionActions>
					<Chips command={command} />
				</AccordionActions>
			</Accordion>
		</Grid>
	);
};

export default memo(Command);
