// src/components/presentational/CommandsPage/Category.tsx
import type { FlattenedCommand } from '@config/types/ApiData';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import Accordion from '@mui/material/Accordion';
import AccordionDetails from '@mui/material/AccordionDetails';
import AccordionSummary from '@mui/material/AccordionSummary';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Command from '@presentational/CommandsPage/Command';
import React, { FC, memo, useCallback } from 'react';

interface CategoryProps {
	categoryName: string;
	searchValue: string;
	commands: FlattenedCommand[];
}

const Category: FC<CategoryProps> = ({ categoryName, commands, searchValue }) => {
	const filterCommands = useCallback((command: FlattenedCommand) => command.name.toLowerCase().includes(searchValue.toLowerCase()), [searchValue]);

	const filteredCategory = commands.filter((command) => command.category === categoryName).filter(filterCommands);

	if (!filteredCategory.length) return null;

	return (
		<Accordion
			defaultExpanded
			TransitionProps={{ unmountOnExit: true }}
			sx={{
				my: 1,
				borderRadius: (theme) => theme.spacing(0.5)
			}}
		>
			<AccordionSummary expandIcon={<ExpandMoreIcon />}>
				<Typography
					variant="h2"
					component="h1"
					sx={{
						fontSize: (theme) => theme.typography.pxToRem(20),
						fontWeight: 'bolder'
					}}
				>
					{categoryName}
				</Typography>
			</AccordionSummary>
			<AccordionDetails>
				<Box display="flex" flexWrap="wrap" flex="1 1 30%" width="100%">
					{filteredCategory.map((command, idx) => (
						<Command key={idx} command={command} />
					))}
				</Box>
			</AccordionDetails>
		</Accordion>
	);
};

export default memo(Category);

// components/presentational/CommandsPage/category.vue
<template>
	<div v-if="filteredCategory.length" class="collapse collapse-arrow my-1 rounded-lg bg-base-200">
		<input type="checkbox" checked />
		<div class="collapse-title text-xl font-bold">
			{{ categoryName }}
		</div>
		<div class="collapse-content">
			<div class="flex flex-wrap">
				<Command v-for="(command, idx) in filteredCategory" :key="idx" :command="command" />
			</div>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { FlattenedCommand } from '~/config/types/ApiData';
import Command from '~/components/presentational/CommandsPage/command.vue';

interface Props {
	categoryName: string;
	searchValue: string;
	commands: FlattenedCommand[];
}

const props = defineProps<Props>();

const filterCommands = (command: FlattenedCommand) => command.name.toLowerCase().includes(props.searchValue.toLowerCase());

const filteredCategory = computed(() => props.commands.filter((command) => command.category === props.categoryName).filter(filterCommands));
</script>

<style scoped>
/* Aggiungi stili personalizzati se necessario */
</style>
