// src/components/presentational/CommandsPage/ExtendedHelpBody.tsx
import GfmReactMarkdown from '@mods/ReactMarkdown/GfmReactMarkdown';
import { EmojiRegexExtractName } from '@utils/constants';
import { memo, type FC } from 'react';

interface ExtendedHelpBodyProps {
	body: string;
}

const ExtendedHelpBody: FC<ExtendedHelpBodyProps> = ({ body }) => {
	return <GfmReactMarkdown source={body.replace(EmojiRegexExtractName, '$1')} />;
};

export default memo(ExtendedHelpBody);

// components/presentational/CommandsPage/extended-help-body.vue
<template>
	<gfm-vue-markdown :source="processedBody" />
</template>

<script lang="ts" setup>
import GfmVueMarkdown from '@/components/mods/markdown/gfm-vue-markdown.vue';
import { defineProps, computed } from 'vue';
import { EmojiRegexExtractName } from '@/utils/constants';

interface ExtendedHelpBodyProps {
	body: string;
}

const props = defineProps<ExtendedHelpBodyProps>();

const processedBody = computed(() => {
	return props.body.replace(EmojiRegexExtractName, '$1');
});
</script>

<style scoped>
/* Aggiungi eventuali stili personalizzati */
</style>
