// src/components/pages/Settings/Filter/FilterWordSettings.tsx
import { useGuildSettingsChangesContext } from '#contexts/Settings/GuildSettingsChangesContext';
import { useGuildSettingsContext } from '#contexts/Settings/GuildSettingsContext';
import Section from '#layout/Settings/Section';
import SimpleGrid from '#mui/SimpleGrid';
import Select from '#selects/Select';
import SelectBoolean from '#selects/SelectBoolean';
import SelectDuration from '#selects/SelectDuration';
import { bitwiseHas, bitwiseSet, removeNonAlphaNumeric, updateSliderValueObj } from '#utils/util';
import { createStyles, makeStyles, Theme } from '@material-ui/core';
import Box from '@material-ui/core/Box';
import Button from '@material-ui/core/Button';
import Chip from '@material-ui/core/Chip';
import MenuItem from '@material-ui/core/MenuItem';
import Paper from '@material-ui/core/Paper';
import Slider from '@material-ui/core/Slider';
import TextField from '@material-ui/core/TextField';
import Typography from '@material-ui/core/Typography';
import React, { FC, Fragment, memo, useState } from 'react';
import { When } from 'react-if';

const useStyles = makeStyles((theme: Theme) =>
	createStyles({
		words: {
			padding: theme.spacing(1),
			'& > *': {
				margin: theme.spacing(1)
			}
		},
		textField: {
			marginRight: theme.spacing(1),
			marginBottom: theme.spacing(1)
		}
	})
);

const FilterWordSettings: FC = () => {
	const [newWord, setNewWord] = useState('');
	const classes = useStyles();
	const { guildSettings } = useGuildSettingsContext();
	const { setGuildSettingsChanges } = useGuildSettingsChangesContext();

	return (
		<Fragment>
			<Section title="Word Filter">
				<SimpleGrid>
					<SelectBoolean
						title={`Filter ${guildSettings.selfmodFilterEnabled ? 'Enabled' : 'Disabled'}`}
						onChange={(event) => setGuildSettingsChanges({ selfmodFilterEnabled: event.target.checked })}
						currentValue={guildSettings.selfmodFilterEnabled}
						description="Whether or not this system should be enabled."
					/>
					<SelectBoolean
						title={`Alerts ${bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b100) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodFilterSoftAction: bitwiseSet(guildSettings.selfmodFilterSoftAction, 0b100, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b100)}
						description="Toggle message alerts in the channel the infraction took place."
					/>
					<SelectBoolean
						title={`Logs ${bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b010) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodFilterSoftAction: bitwiseSet(guildSettings.selfmodFilterSoftAction, 0b010, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b010)}
						description="Toggle message logs in the moderation logs channel."
					/>
					<SelectBoolean
						title={`Deletes ${bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b001) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodFilterSoftAction: bitwiseSet(guildSettings.selfmodFilterSoftAction, 0b001, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b001)}
						description="Toggle message deletions."
					/>
				</SimpleGrid>
			</Section>
			<Section title="Punishments">
				<SimpleGrid direction="row" justify="flex-start">
					<Select
						title="Action"
						helperText="The action to perform as punishment"
						value={guildSettings.selfmodFilterHardAction}
						onChange={(e) => setGuildSettingsChanges({ selfmodFilterHardAction: e.target.value })}
					>
						<MenuItem value={0}>None</MenuItem>
						<MenuItem value={1}>Warning</MenuItem>
						<MenuItem value={2}>Kick</MenuItem>
						<MenuItem value={3}>Mute</MenuItem>
						<MenuItem value={4}>Softban</MenuItem>
						<MenuItem value={5}>Ban</MenuItem>
					</Select>
					<SelectDuration
						value={guildSettings.selfmodFilterHardActionDuration}
						min={1000}
						onChange={(duration) => setGuildSettingsChanges({ selfmodFilterHardActionDuration: duration })}
					/>
				</SimpleGrid>
				<Typography>Maximum Threshold</Typography>
				<Slider
					value={guildSettings.selfmodFilterThresholdMaximum}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('selfmodFilterThresholdMaximum', value))}
					aria-labelledby="Words selfmod filter maximum threshold slider"
					valueLabelDisplay="auto"
					min={0}
					max={60}
				/>
				<Typography>Threshold Duration (in seconds)</Typography>
				<Slider
					value={guildSettings.selfmodFilterThresholdDuration / 1000}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('selfmodFilterThresholdDuration', value, 1000))}
					aria-labelledby="Word selfmod filter threshold duration slider"
					valueLabelDisplay="auto"
					min={0}
					max={120}
				/>
			</Section>
			<Section title="Filtered Words">
				<form
					onSubmit={(e) => {
						e.preventDefault();
						const word = removeNonAlphaNumeric(newWord).toLowerCase();
						if (word.length < 3 || guildSettings.selfmodFilterRaw.includes(word)) return;
						setGuildSettingsChanges({
							selfmodFilterRaw: [...guildSettings.selfmodFilterRaw, word]
						});
						setNewWord('');
					}}
				>
					<Box display="flex" mb={2} alignContent="center" alignItems="center" justifyContent="flex-start">
						<TextField
							classes={{ root: classes.textField }}
							label="Add Word"
							value={newWord}
							onChange={(e) => setNewWord(e.target.value)}
						/>
						<Button type="submit" variant="contained" color="primary">
							Confirm
						</Button>
					</Box>
				</form>

				<When condition={guildSettings.selfmodFilterRaw.length !== 0}>
					<Paper classes={{ root: classes.words }}>
						{guildSettings.selfmodFilterRaw.map((word) => (
							<Chip
								color="primary"
								key={word}
								label={word}
								onDelete={() =>
									setGuildSettingsChanges({
										selfmodFilterRaw: guildSettings.selfmodFilterRaw.filter((item) => item !== word)
									})
								}
							/>
						))}
					</Paper>
				</When>
			</Section>
		</Fragment>
	);
};

export default memo(FilterWordSettings);

// components/pages/Settings/Filter/FilterWordSettings.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useGuildSettingsChanges } from '@/composables/settings/useGuildSettingsChanges.ts';
import { useGuildSettings } from '@/composables/settings/useGuildSettings';
import { bitwiseHas, bitwiseSet, removeNonAlphaNumeric, updateSliderValueObj } from '@/utils/util';

const { guildSettings } = useGuildSettings();
const { setGuildSettingsChanges } = useGuildSettingsChanges();

const newWord = ref('');

const addWord = () => {
	const word = removeNonAlphaNumeric(newWord.value).toLowerCase();
	if (word.length < 3 || guildSettings.value.selfmodFilterRaw.includes(word)) return;
	setGuildSettingsChanges({
		selfmodFilterRaw: [...guildSettings.value.selfmodFilterRaw, word]
	});
	newWord.value = '';
};

const removeWord = (wordToRemove: string) => {
	setGuildSettingsChanges({
		selfmodFilterRaw: guildSettings.value.selfmodFilterRaw.filter((word) => word !== wordToRemove)
	});
};

const updateSoftAction = (bit: number, checked: boolean) => {
	setGuildSettingsChanges({
		selfmodFilterSoftAction: bitwiseSet(guildSettings.value.selfmodFilterSoftAction, bit, checked)
	});
};

const thresholdMaximum = computed({
	get: () => guildSettings.value.selfmodFilterThresholdMaximum,
	set: (value) => setGuildSettingsChanges(updateSliderValueObj('selfmodFilterThresholdMaximum', value))
});

const thresholdDuration = computed({
	get: () => guildSettings.value.selfmodFilterThresholdDuration / 1000,
	set: (value) => setGuildSettingsChanges(updateSliderValueObj('selfmodFilterThresholdDuration', value, 1000))
});
</script>

<template>
	<div>
		<Section title="Word Filter">
			<SimpleGrid>
				<SelectBoolean
					:title="`Filter ${guildSettings.selfmodFilterEnabled ? 'Enabled' : 'Disabled'}`"
					@change="setGuildSettingsChanges({ selfmodFilterEnabled: $event })"
					:current-value="guildSettings.selfmodFilterEnabled"
					description="Whether or not this system should be enabled."
				/>
				<SelectBoolean
					:title="`Alerts ${bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b100) ? 'Enabled' : 'Disabled'}`"
					@change="updateSoftAction(0b100, $event)"
					:current-value="bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b100)"
					description="Toggle message alerts in the channel the infraction took place."
				/>
				<SelectBoolean
					:title="`Logs ${bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b010) ? 'Enabled' : 'Disabled'}`"
					@change="updateSoftAction(0b010, $event)"
					:current-value="bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b010)"
					description="Toggle message logs in the moderation logs channel."
				/>
				<SelectBoolean
					:title="`Deletes ${bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b001) ? 'Enabled' : 'Disabled'}`"
					@change="updateSoftAction(0b001, $event)"
					:current-value="bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b001)"
					description="Toggle message deletions."
				/>
			</SimpleGrid>
		</Section>

		<Section title="Punishments">
			<SimpleGrid direction="row" justify-content="flex-start">
				<Select
					title="Action"
					helper-text="The action to perform as punishment"
					:value="guildSettings.selfmodFilterHardAction"
					@change="setGuildSettingsChanges({ selfmodFilterHardAction: $event })"
				>
					<option :value="0">None</option>
					<option :value="1">Warning</option>
					<option :value="2">Kick</option>
					<option :value="3">Mute</option>
					<option :value="4">Softban</option>
					<option :value="5">Ban</option>
				</Select>
				<SelectDuration
					:value="guildSettings.selfmodFilterHardActionDuration"
					:min="1000"
					@change="setGuildSettingsChanges({ selfmodFilterHardActionDuration: $event })"
				/>
			</SimpleGrid>
			<div>
				<p>Maximum Threshold</p>
				<input v-model="thresholdMaximum" type="range" min="0" max="60" />
			</div>
			<div>
				<p>Threshold Duration (in seconds)</p>
				<input v-model="thresholdDuration" type="range" min="0" max="120" />
			</div>
		</Section>

		<Section title="Filtered Words">
			<form @submit.prevent="addWord">
				<div class="mb-2 flex items-center">
					<input v-model="newWord" class="mb-1 mr-1" placeholder="Add Word" />
					<button type="submit" class="btn btn-primary">Confirm</button>
				</div>
			</form>

			<div v-if="guildSettings.selfmodFilterRaw.length !== 0" class="p-1">
				<span
					v-for="word in guildSettings.selfmodFilterRaw"
					:key="word"
					class="badge badge-primary m-1 cursor-pointer"
					@click="removeWord(word)"
				>
					{{ word }}
				</span>
			</div>
		</Section>
	</div>
</template>
