// components/pages/Settings/general-settings.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useForm } from 'vee-validate';
import { object, string } from 'yup';
import { useGuildSettingsChanges } from '~/composables/settings/useGuildSettingsChanges';
import { useGuildSettings } from '~/composables/settings/useGuildSettings';
import Section from '~/layouts/settings/section.vue';

const props = defineProps<{
	languages: string[];
}>();

const { guildSettings } = useGuildSettings();
const { setGuildSettingsChanges } = useGuildSettingsChanges();

const validationSchema = object({
	prefix: string().required('Setting a prefix is required').min(1, 'Prefix has a minimum length of 1').max(11, 'Prefix has a maximum length of 10')
});

const { handleSubmit, errors, values } = useForm({
	validationSchema,
	initialValues: {
		prefix: guildSettings.value.prefix
	}
});

const onSubmit = handleSubmit((values) => {
	setGuildSettingsChanges({ prefix: values.prefix });
});

const mapLanguageKeysToNames = (langKey: string): [string] | [string, string] => {
	const supportedLanguagesMap: Record<string, [string] | [string, string]> = {
		'ckb-IR': ['Kurdiya Navîn (Iranran)', 'Kurdish'],
		'de-DE': ['Deutsch', 'German'],
		'en-GB': ['British English', 'English, United Kingdom'],
		'en-US': ['American English', 'English, United States'],
		'es-ES': ['Español', 'Spanish'],
		'fa-IR': ['فارسی', 'Persian'],
		'fr-FR': ['Français', 'French'],
		'hi-IN': ['हिंदी', 'Hindi'],
		'hi-Latn-IN': ['Hinglish', 'Hindi (Latin Alphabet)'],
		'it-IT': ['Italiano', 'Italian'],
		'ja-JP': ['日本語', 'Japanese'],
		'nb-NO': ['Bokmål', 'Norwegian Bokmal'],
		'nl-NL': ['Nederlands', 'Dutch'],
		'pt-BR': ['Português Brasileiro', 'Portuguese, Brazilian'],
		'ro-RO': ['Română', 'Romanian'],
		'ru-RU': ['Pусский', 'Russian'],
		'sl-SI': ['Slovenščina', 'Slovenian'],
		'tr-TR': ['Türkçe', 'Turkish']
	};

	return supportedLanguagesMap[langKey] ?? [langKey];
};
</script>

<template>
	<Section title="General Settings">
		<form @submit.prevent="onSubmit" class="space-y-4">
			<div class="form-control">
				<label class="label" for="prefix">
					<span class="label-text">Prefix</span>
				</label>
				<input
					id="prefix"
					v-model="values.prefix"
					type="text"
					placeholder="This is your server's prefix, use it to trigger Skyra commands."
					class="input input-bordered"
					:class="{ 'input-error': errors.prefix }"
				/>
				<label v-if="errors.prefix" class="label">
					<span class="label-text-alt text-error">{{ errors.prefix }}</span>
				</label>
			</div>

			<div class="form-control">
				<label class="label" for="language">
					<span class="label-text">Language</span>
				</label>
				<select
					id="language"
					v-model="guildSettings.language"
					class="select select-bordered w-full"
					@change="(e: Event) => setGuildSettingsChanges({ language: (e.target as HTMLSelectElement).value })"
				>
					<option v-for="langKey in languages" :key="langKey" :value="langKey">
						{{ mapLanguageKeysToNames(langKey).join(' - ') }}
					</option>
				</select>
				<label class="label">
					<span class="label-text-alt">Select the language you want for this guild</span>
				</label>
			</div>

			<button type="submit" class="btn btn-primary">Save Prefix</button>
		</form>
	</Section>
</template>

// src/components/pages/Settings/GeneralSettings.tsx
import { useMobileContext } from '@contexts/MobileContext';
import { useGuildSettingsChangesContext } from '@contexts/Settings/GuildSettingsChangesContext';
import { useGuildSettingsContext } from '@contexts/Settings/GuildSettingsContext';
import Section from '@layout/Settings/Section';
import SimpleGrid from '@material/SimpleGrid';
import AutoSavingForm from '@mods/Formik/AutoSaveForm';
import FormikTextField from '@mods/Formik/FormikTextField';
import { ListItemText, MenuItem } from '@mui/material';
import Select from '@selects/Select';
import { memo, type FC } from 'react';
import { object, SchemaOf, string } from 'yup';

interface GeneralSettingsProps {
	languages: string[];
}

interface FormShape {
	prefix: string;
}

const validationSchema: SchemaOf<FormShape> = object({
	prefix: string().required('Setting a prefix is required').min(1, 'Prefix has a minimum length of 1').max(11, 'Prefix has a maximum length of 10')
});

const GeneralSettings: FC<GeneralSettingsProps> = ({ languages }) => {
	const { guildSettings } = useGuildSettingsContext();
	const { setGuildSettingsChanges } = useGuildSettingsChangesContext();
	const { isMobile } = useMobileContext();

	const mapLanguageKeysToNames = (langKey: string): [string] | [string, string] => {
		const supportedLanguagesMap: Record<string, [string] | [string, string]> = {
			'ckb-IR': ['Kurdiya Navîn (Iranran)', 'Kurdish'],
			'de-DE': ['Deutsch', 'German'],
			'en-GB': ['British English', 'English, United Kingdom'],
			'en-US': ['American English', 'English, United States'],
			'es-ES': ['Español', 'Spanish'],
			'fa-IR': ['فارسی', 'Persian'],
			'fr-FR': ['Français', 'French'],
			'hi-IN': ['हिंदी', 'Hindi'],
			'hi-Latn-IN': ['Hinglish', 'Hindi (Latin Alphabet)'],
			'it-IT': ['Italiano', 'Italian'],
			'ja-JP': ['日本語', 'Japanese'],
			'nb-NO': ['Bokmål', 'Norwegian Bokmal'],
			'nl-NL': ['Nederlands', 'Dutch'],
			'pt-BR': ['Português Brasileiro', 'Portuguese, Brazilian'],
			'ro-RO': ['Română', 'Romanian'],
			'ru-RU': ['Pусский', 'Russian'],
			'sl-SI': ['Slovenščina', 'Slovenian'],
			'tr-TR': ['Türkçe', 'Turkish']
		};

		return supportedLanguagesMap[langKey] ?? [langKey];
	};

	return (
		<Section title="General Settings">
			<SimpleGrid
				direction="row"
				justifyContent="flex-start"
				gridItemProps={{
					xs: 12,
					sm: 12,
					md: 12,
					lg: 12,
					xl: 12
				}}
			>
				<AutoSavingForm
					validationSchema={validationSchema}
					initialValues={{ prefix: guildSettings.prefix }}
					onSubmit={(values, formikHelpers) => {
						formikHelpers.setSubmitting(true);
						setGuildSettingsChanges({ prefix: values.prefix });

						formikHelpers.setSubmitting(false);
					}}
				>
					<FormikTextField<FormShape>
						name="prefix"
						label="Prefix"
						TextFieldProps={{
							placeholder: "This is your server's prefix, use it to trigger Skyra commands."
						}}
					/>
				</AutoSavingForm>
				<Select
					title="Language"
					FormControlProps={{ sx: { mt: 5 } }}
					helperText="Select the language you want for this guild"
					value={guildSettings.language}
					onChange={(e) => setGuildSettingsChanges({ language: e.target.value })}
					fullWidth
					autoWidth={isMobile}
					MenuProps={{
						...(isMobile && {
							anchorOrigin: {
								vertical: 'top',
								horizontal: 'right'
							}
						})
					}}
				>
					{languages.map((langKey) => {
						const [commonName, englishName] = mapLanguageKeysToNames(langKey);

						return (
							<MenuItem key={langKey} value={langKey} dense>
								<ListItemText primary={commonName} secondary={englishName} />
							</MenuItem>
						);
					})}
				</Select>
			</SimpleGrid>
		</Section>
	);
};

export default memo(GeneralSettings);
