// src/components/pages/GuildsPage.tsx
import { useAuthenticated } from '@contexts/AuthenticationContext';
import { useDiscordPack } from '@contexts/DiscordPackContext';
import { useMobileContext } from '@contexts/MobileContext';
import GeneralPage from '@layout/General';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import { FilteredGuildCards } from '@presentational/GuildCard';
import type { NextPage } from 'next';
import React from 'react';

const GuildsPage: NextPage = () => {
	const authenticated = useAuthenticated();
	const pack = useDiscordPack();
	const { isMobile } = useMobileContext();

	return (
		<>
			<GeneralPage>
				<Container
					sx={{
						display: 'flex',
						flexDirection: 'column',
						justifyContent: 'center',
						alignContent: 'center',
						alignItems: 'center',
						height: {
							sm: 'calc(100vh - 200px - 128px)',
							xs: authenticated ? 'unset' : 'calc(100vh - 200px - 128px)'
						}
					}}
				>
					<Box display="flex" flexWrap="wrap" flexDirection="row" justifyContent="center" alignItems="center">
						{authenticated ? (
							FilteredGuildCards(pack)
						) : (
							<Typography
								variant="h1"
								sx={{
									fontSize: {
										md: (theme) => theme.typography.pxToRem(40),
										xs: (theme) => theme.typography.pxToRem(30)
									}
								}}
							>
								Sorry, you are not logged in and can therefore not view this page. Please{' '}
								{isMobile ? 'open the menu button at the top left then click "Login"' : 'click the "Login" button at the top right'}{' '}
								to login with Discord
							</Typography>
						)}
					</Box>
				</Container>
			</GeneralPage>
		</>
	);
};

export default GuildsPage;

// components/pages/GuildsPage.vue
<script setup lang="ts">
import FilteredGuildCards from '~/components/presentational/guild-card.vue';

const { loggedIn, session } = useAuth();

const { isMobile } = useDevice();
</script>

<template>
	<div class="container mx-auto flex h-screen flex-col items-center justify-center sm:h-[calc(100vh-328px)]">
		<div class="flex flex-wrap items-center justify-center">
			<template v-if="loggedIn">
				<component :is="card" v-for="card in new FilteredGuildCards(session)" :key="card.key" />
			</template>
			<p v-else class="text-center text-2xl md:text-4xl">
				Sorry, you are not logged in and can therefore not view this page. Please click the "Login" button at the top right to login with
				Discord
			</p>
		</div>
	</div>
</template>
