// src/components/material/DialogSearchBar.tsx
import SearchIcon from '@mui/icons-material/Search';
import type { InputBaseProps } from '@mui/material/InputBase';
import React, { FC, memo } from 'react';
import { Box, InputBase } from '@mui/material';

const DialogSearchBar: FC<InputBaseProps> = ({ onChange }) => {
	return (
		<Box
			sx={{
				display: 'flex',
				alignItems: 'center',
				alignContent: 'center',
				p: 1.25,
				my: 0,
				mx: 1.25
			}}
		>
			<SearchIcon
				sx={{
					mr: 1.25
				}}
			/>
			<InputBase
				autoFocus
				autoCapitalize="false"
				autoComplete="off"
				autoCorrect="false"
				results={4}
				placeholder="Search…"
				onChange={onChange}
				inputProps={{ 'aria-label': 'search input' }}
			/>
		</Box>
	);
};

export default memo(DialogSearchBar);

// components/layouts/material/dialog-search-bar.vue
<template>
	<div class="mx-5 my-0 flex items-center p-3">
		<NuxtIcon name="mdi-magnify" class="mr-5" />
		<input
			v-bind="otherProps"
			autofocus
			autocapitalize="false"
			autocomplete="off"
			autocorrect="false"
			results="4"
			placeholder="Search…"
			aria-label="search input"
			class="input input-bordered w-full"
			@input="handleInput"
		/>
	</div>
</template>

<script setup lang="ts">
import { defineProps, defineEmits } from 'vue';

interface InputBaseProps {
	onChange?: (event: Event) => void;
	[key: string]: any;
}

const props = defineProps<InputBaseProps>();
const emit = defineEmits(['change']);

const handleInput = (event: Event) => {
	if (props.onChange) {
		props.onChange(event);
	}
	emit('change', event);
};

const { onChange, ...otherProps } = props;
</script>

<style scoped>
.input {
	@apply w-full;
}
</style>
