// src/components/material/UiSearchBar.tsx
import ClearIcon from '@mui/icons-material/Clear';
import SearchIcon from '@mui/icons-material/Search';
import type { InputProps } from '@mui/material/Input';
import type { PaperProps } from '@mui/material/Paper';
import type { Theme } from '@mui/material/styles';
import {
	cloneElement,
	forwardRef,
	memo,
	useCallback,
	useEffect,
	useImperativeHandle,
	useRef,
	useState,
	type ChangeEvent as ReactChangeEvent,
	type CSSProperties,
	type FocusEvent as ReactFocusEvent,
	type KeyboardEvent as ReactKeyboardEvent
} from 'react';

import { Box, IconButton, Input, Paper } from '@mui/material';

interface SearchBarProps extends Omit<InputProps, 'onChange'> {
	/**
	 * Whether to clear search on escape.
	 */
	cancelOnEscape?: boolean;
	/**
	 * Custom top-level class.
	 */
	className?: string;
	/**
	 * Disables text field.
	 */
	disabled?: boolean;
	/**
	 * Fired when the text value changes.
	 */
	onChange?(query: string): void;
	/**
	 * Fired when the search is cancelled.
	 */
	onCancelSearch?(): void;
	/**
	 * Fired when the search icon is clicked.
	 */
	onRequestSearch?(value?: string): void;
	/**
	 * Override the inline-styles of the root element.
	 */
	style?: CSSProperties;
	/**
	 * The value of the text field.
	 */
	value?: string;
	/**
	 * Additional props to apply to the Paper component
	 */
	PaperProps?: PaperProps;
}

interface SearchBarHandle {
	focus(): void;
	blur(): void;
}

const UiSearchBar = forwardRef<SearchBarHandle, SearchBarProps>(
	(
		{
			cancelOnEscape,
			className = '',
			disabled = false,
			onCancelSearch,
			onRequestSearch,
			style,
			onFocus,
			onBlur,
			onChange,
			onKeyUp,
			value = '',
			PaperProps,
			placeholder
		},
		ref
	) => {
		const inputRef = useRef<HTMLInputElement>();
		const [innerValue, setInnerValue] = useState<string>(value ?? '');

		useEffect(() => {
			setInnerValue(value);
		}, [value]);

		const handleFocus = useCallback(
			(e: ReactFocusEvent<HTMLInputElement | HTMLTextAreaElement, Element>) => {
				if (onFocus) {
					onFocus(e);
				}
			},
			[onFocus]
		);

		const handleBlur = useCallback(
			(e: ReactFocusEvent<HTMLInputElement | HTMLTextAreaElement, Element>) => {
				setInnerValue((v) => v.trim());
				if (onBlur) {
					onBlur(e);
				}
			},
			[onBlur]
		);

		const handleInput = useCallback(
			(e: ReactChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
				setInnerValue(e.target.value);
				if (onChange) {
					onChange(e.target.value);
				}
			},
			[onChange]
		);

		const handleCancel = useCallback(() => {
			setInnerValue('');
			if (onCancelSearch) {
				onCancelSearch();
			}
		}, [onCancelSearch]);

		const handleRequestSearch = useCallback(() => {
			if (onRequestSearch) {
				onRequestSearch(innerValue);
			}
		}, [onRequestSearch, innerValue]);

		const handleKeyUp = useCallback(
			(e: ReactKeyboardEvent<HTMLInputElement | HTMLTextAreaElement>) => {
				if (e.charCode === 13 || e.key === 'Enter') {
					handleRequestSearch();
				} else if (cancelOnEscape && (e.charCode === 27 || e.key === 'Escape')) {
					handleCancel();
				}
				if (onKeyUp) {
					onKeyUp(e);
				}
			},
			[handleRequestSearch, cancelOnEscape, handleCancel, onKeyUp]
		);

		useImperativeHandle(ref, () => ({
			focus: () => {
				inputRef.current!.focus();
			},
			blur: () => {
				inputRef.current!.blur();
			}
		}));

		return (
			<Paper
				className={className}
				style={style}
				{...PaperProps}
				sx={{
					height: (theme) => theme.spacing(6),
					zIndex: (theme) => theme.zIndex.appBar - 1,
					backgroundColor: (theme) => theme.palette.secondary.light,
					mb: 1,
					display: 'flex',
					justifyContent: 'space-between',
					position: 'sticky',
					top: {
						md: (theme) => theme.spacing(9),
						xs: (theme) => theme.spacing(8.5)
					}
				}}
			>
				<Box
					sx={{
						margin: 'auto 16px',
						width: (theme) => `calc(100% - ${theme.spacing(6 + 4)})` // 6 button + 4 margin
					}}
				>
					<Input
						placeholder={placeholder}
						inputRef={inputRef}
						onBlur={handleBlur}
						value={innerValue}
						onChange={handleInput}
						onKeyUp={handleKeyUp}
						onFocus={handleFocus}
						fullWidth
						disableUnderline
						disabled={disabled}
						sx={{
							width: '100%',
							color: (theme) => theme.palette.common.white
						}}
					/>
				</Box>
				<IconButton
					onClick={handleRequestSearch}
					disabled={disabled}
					size="large"
					sx={{
						color: (theme) => theme.palette.action.active,
						transform: value === '' ? 'scale(0,0)' : 'scale(1, 1)',
						opacity: value === '' ? 0 : 1,
						mr: -1,
						transition: (theme) =>
							theme.transitions.create(['transform', 'color'], {
								duration: theme.transitions.duration.shorter,
								easing: theme.transitions.easing.easeInOut
							})
					}}
				>
					{cloneElement(<SearchIcon />, {
						sx: (theme: Theme) => ({
							color: theme.palette.common.white,
							transition: theme.transitions.create(['opacity'], {
								duration: theme.transitions.duration.shorter,
								easing: theme.transitions.easing.easeInOut
							})
						})
					})}
				</IconButton>
				<IconButton
					onClick={handleCancel}
					sx={{
						color: (theme) => theme.palette.action.active,
						transform: value === '' ? 'scale(0,0)' : 'scale(1, 1)',
						opacity: value === '' ? 0 : 1,
						transition: (theme) =>
							theme.transitions.create(['transform', 'color'], {
								duration: theme.transitions.duration.shorter,
								easing: theme.transitions.easing.easeInOut
							})
					}}
					disabled={disabled}
					size="large"
				>
					{cloneElement(<ClearIcon />, {
						sx: (theme: Theme) => ({
							color: theme.palette.common.white,
							transition: theme.transitions.create(['opacity'], {
								duration: theme.transitions.duration.shorter,
								easing: theme.transitions.easing.easeInOut
							})
						})
					})}
				</IconButton>
			</Paper>
		);
	}
);

export default memo(UiSearchBar);

// components/layouts/material/ui-search-bar.vue
<template>
	<div
		class="paper bg-secondary-light sticky mb-1 flex justify-between"
		:class="className"
		:style="[paperStyle, { top: useDevice().isMobile ? '34px' : '36px' }]"
	>
		<div class="mx-4 w-full">
			<input
				ref="inputRef"
				:placeholder="placeholder"
				:value="modelValue"
				:disabled="disabled"
				class="input input-ghost w-full text-white focus:outline-none"
				@input="handleInput"
				@blur="handleBlur"
				@keyup="handleKeyUp"
				@focus="handleFocus"
			/>
		</div>
		<button
			:disabled="disabled"
			class="btn btn-circle btn-ghost transition-all duration-200"
			:class="{ 'scale-0 opacity-0': !modelValue, 'scale-100 opacity-100': modelValue }"
			@click="handleRequestSearch"
		>
			<i class="fas fa-search text-white" />
		</button>
		<button
			:disabled="disabled"
			class="btn btn-circle btn-ghost transition-all duration-200"
			:class="{ 'scale-0 opacity-0': !modelValue, 'scale-100 opacity-100': modelValue }"
			@click="handleCancel"
		>
			<i class="fas fa-times text-white" />
		</button>
	</div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';

interface Props {
	modelValue: string;
	cancelOnEscape?: boolean;
	className?: string;
	disabled?: boolean;
	placeholder?: string;
	paperStyle?: Record<string, string>;
}

const props = withDefaults(defineProps<Props>(), {
	modelValue: '',
	cancelOnEscape: false,
	className: '',
	disabled: false,
	placeholder: '',
	paperStyle: () => ({})
});

const emit = defineEmits<{
	(e: 'update:modelValue', value: string): void;
	(e: 'cancelSearch'): void;
	(e: 'requestSearch', value: string): void;
	(e: 'focus', event: FocusEvent): void;
	(e: 'blur', event: FocusEvent): void;
}>();

const inputRef = ref<HTMLInputElement | null>(null);

const handleInput = (e: Event) => {
	const target = e.target as HTMLInputElement;
	emit('update:modelValue', target.value);
};

const handleBlur = (e: FocusEvent) => {
	emit('blur', e);
};

const handleFocus = (e: FocusEvent) => {
	emit('focus', e);
};

const handleCancel = () => {
	emit('update:modelValue', '');
	emit('cancelSearch');
};

const handleRequestSearch = () => {
	emit('requestSearch', props.modelValue);
};

const handleKeyUp = (e: KeyboardEvent) => {
	if (e.key === 'Enter') {
		handleRequestSearch();
	} else if (props.cancelOnEscape && e.key === 'Escape') {
		handleCancel();
	}
};

// Expose focus and blur methods
defineExpose({
	focus: () => inputRef.value?.focus(),
	blur: () => inputRef.value?.blur()
});

// Watch for external value changes
watch(
	() => props.modelValue,
	(newValue) => {
		if (inputRef.value) {
			inputRef.value.value = newValue;
		}
	}
);

onMounted(() => {
	if (inputRef.value) {
		inputRef.value.value = props.modelValue;
	}
});
</script>

<style scoped>
.paper {
	z-index: 1099; /* Adjust as needed */
	height: 48px; /* Equivalent to theme.spacing(6) */
}
</style>
