// src/components/presentational/GuildSettings.tsx
import type { FlattenedCommand } from '@config/types/ApiData';
import { FilterRoutes, GuildRoutes } from '@config/types/GuildRoutes';
import Dashboard from '@layout/Settings/Dashboard';
import ChannelSettings from '@pages/Settings/ChannelSettings';
import DisabledCommandSettings from '@pages/Settings/DisabledCommandSettings';
import EventSettings from '@pages/Settings/EventSettings';
import FilterCapitalsSettings from '@pages/Settings/Filter/FilterCapitalsSettings';
import FilterInvitesSettings from '@pages/Settings/Filter/FilterInvitesSettings';
import FilterLinksSettings from '@pages/Settings/Filter/FilterLinksSettings';
import FilterMessagesSettings from '@pages/Settings/Filter/FilterMessagesSettings';
import FilterNewLineSettings from '@pages/Settings/Filter/FilterNewLineSettings';
import FilterReactionSettings from '@pages/Settings/Filter/FilterReactionSettings';
import FilterWordSettings from '@pages/Settings/Filter/FilterWordSettings';
import GeneralSettings from '@pages/Settings/GeneralSettings';
import ModerationSettings from '@pages/Settings/ModerationSettings';
import RoleSettings from '@pages/Settings/RoleSettings';
import Loading from '@presentational/Loading';
import { ExpirableLocalStorageStructure, LocalStorageKeys } from '@utils/constants';
import { Time } from '@utils/skyraUtils';
import { apiFetch, loadState, saveState } from '@utils/util';
import { useRouter } from 'next/router';
import { memo, useCallback, useEffect, useState, type FC } from 'react';

interface GuildSettingsProps {}

const GuildSettings: FC<GuildSettingsProps> = () => {
	const router = useRouter();

	const [loading, setLoading] = useState(true);
	const [commands, setCommands] = useState<FlattenedCommand[]>([]);
	const [languages, setLanguages] = useState<string[]>([]);

	const [guildId, ...path] = router.query.id ?? ['', ['']];
	const joinedPath = path.join('/');

	const fetchCommandsAndLanguages = useCallback(async () => {
		setLoading(true);

		const commandsFromLocalStorage = loadState<ExpirableLocalStorageStructure<FlattenedCommand[]>>(LocalStorageKeys.Commands);
		if (commandsFromLocalStorage && (process.env.NODE_ENV === 'development' || commandsFromLocalStorage.expire > Date.now())) {
			setCommands(commandsFromLocalStorage.data);
		} else {
			const commandsData = await apiFetch<FlattenedCommand[]>('/commands');
			setCommands(commandsData);
			saveState<ExpirableLocalStorageStructure<FlattenedCommand[]>>(LocalStorageKeys.Commands, {
				expire: Date.now() + Time.Day * 6,
				data: commandsData
			});
		}

		const languagesFromLocalStorage = loadState<ExpirableLocalStorageStructure<string[]>>(LocalStorageKeys.Languages);
		if (languagesFromLocalStorage && (process.env.NODE_ENV === 'development' || languagesFromLocalStorage.expire > Date.now())) {
			setLanguages(languagesFromLocalStorage.data);
		} else {
			const languagesData = await apiFetch<string[]>('/languages');
			setLanguages(languagesData);
			saveState<ExpirableLocalStorageStructure<string[]>>(LocalStorageKeys.Languages, {
				expire: Date.now() + Time.Day * 6,
				data: languagesData
			});
		}

		setLoading(false);
	}, []);

	useEffect(() => {
		void fetchCommandsAndLanguages();
	}, [fetchCommandsAndLanguages]);

	const renderSettingsPath = () => {
		switch (joinedPath as GuildRoutes & FilterRoutes) {
			case GuildRoutes.Channels:
				return <ChannelSettings />;
			case GuildRoutes.DisabledCommands:
				return <DisabledCommandSettings setCommands={setCommands} commands={commands} />;
			case GuildRoutes.Events:
				return <EventSettings />;
			case GuildRoutes.Moderation:
				return <ModerationSettings />;
			case GuildRoutes.Roles:
				return <RoleSettings />;
			case FilterRoutes.Capitals:
				return <FilterCapitalsSettings />;
			case FilterRoutes.Invites:
				return <FilterInvitesSettings />;
			case FilterRoutes.Links:
				return <FilterLinksSettings />;
			case FilterRoutes.MessageDuplication:
				return <FilterMessagesSettings />;
			case FilterRoutes.NewLines:
				return <FilterNewLineSettings />;
			case FilterRoutes.Reactions:
				return <FilterReactionSettings />;
			case FilterRoutes.Words:
				return <FilterWordSettings />;
			default:
				return <GeneralSettings languages={languages} />;
		}
	};

	return (
		<>
			<Loading loading={loading} />
			<Dashboard guildId={guildId}>{renderSettingsPath()}</Dashboard>
		</>
	);
};

export default memo(GuildSettings);

// components/presentational/guild-settings.vue
<template>
	<div>
		<Loading v-if="loading" />
		<Dashboard v-else :guild-id="guildId">
			<component :is="settingsComponent" :commands="commands" :languages="languages" />
		</Dashboard>
	</div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, defineAsyncComponent } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { LocalStorageKeys, type ExpirableLocalStorageStructure } from '~/utils/constants.ts';
import type { FlattenedCommand } from '~/config/types/ApiData.ts';
import { useLocalStorage } from '@vueuse/core';
import { Time } from '~/utils/wolfstarUtils';

// Components
const Loading = defineAsyncComponent(() => import('./loading.vue'));
const Dashboard = defineAsyncComponent(() => import('~/layouts/settings/dashboard-layout.vue'));

const route = useRoute();

const guildId = ref(route.params.guildId as string);

const loading = ref(true);
const commands = ref<FlattenedCommand[]>([]);
const languages = ref<string[]>([]);

const fetchCommandsAndLanguages = async () => {
	loading.value = true;

	// Fetch and cache commands (same logic as before)
	const commandsFromLocalStorage = useLocalStorage<ExpirableLocalStorageStructure<FlattenedCommand[]>>(LocalStorageKeys.Commands, {
		expire: 0,
		data: []
	});
	if (commandsFromLocalStorage.value.expire > Date.now() || import.meta.env.DEV) {
		commands.value = commandsFromLocalStorage.value.data;
	} else {
		const commandsData = await $fetch<FlattenedCommand[]>('/api/commands');
		commands.value = commandsData;
		commandsFromLocalStorage.value = {
			expire: Date.now() + Time.Day * 6,
			data: commandsData
		};
	}

	// Fetch and cache languages
	const languagesFromLocalStorage = useLocalStorage<ExpirableLocalStorageStructure<string[]>>(LocalStorageKeys.Languages, {
		expire: 0,
		data: []
	});
	if (languagesFromLocalStorage.value.expire > Date.now() || import.meta.env.DEV) {
		languages.value = languagesFromLocalStorage.value.data;
	} else {
		const languagesData = await $fetch<string[]>('/api/languages');
		languages.value = languagesData;
		languagesFromLocalStorage.value = {
			expire: Date.now() + Time.Day * 6,
			data: languagesData
		};
	}

	loading.value = false;
};

onMounted(fetchCommandsAndLanguages);

const joinedPath = computed(() => route.fullPath.split('/').slice(2).join('/') || '');

const settingsComponent = computed(() => {
	switch (joinedPath.value) {
		case 'channels':
			return defineAsyncComponent(() => import('~/components/pages/Settings/channel-settings.vue'));
		case 'disabled-commands':
			return defineAsyncComponent(() => import('~/components/pages/Settings/disabled-commands-settings.vue'));
		case 'events':
			return defineAsyncComponent(() => import('~/components/pages/Settings/event-settings.vue'));
		case 'moderation':
			return defineAsyncComponent(() => import('~/components/pages/Settings/moderation-settings.vue'));
		case 'roles':
			return defineAsyncComponent(() => import('~/components/pages/Settings/role-settings.vue'));
		case 'filter/capitals':
			return defineAsyncComponent(() => import('~/components/pages/Settings/Filter/FilterCapitalsSettings.vue'));
		case 'filter/invites':
			return defineAsyncComponent(() => import('~/components/pages/Settings/Filter/FilterInvitesSettings.vue'));
		case 'filter/links':
			return defineAsyncComponent(() => import('~/components/pages/Settings/Filter/FilterLinksSettings.vue'));
		case 'filter/message-duplication':
			return defineAsyncComponent(() => import('~/components/pages/Settings/Filter/FilterMessagesSettings.vue'));
		case 'filter/new-lines':
			return defineAsyncComponent(() => import('~/components/pages/Settings/Filter/FilterNewLineSettings.vue'));
		case 'filter/reactions':
			return defineAsyncComponent(() => import('~/components/pages/Settings/Filter/FilterReactionSettings.vue'));
		case 'filter/words':
			return defineAsyncComponent(() => import('~/components/pages/Settings/Filter/FilterWordSettings.vue'));
		default:
			return defineAsyncComponent(() => import('~/components/pages/Settings/general-settings.vue'));
	}
});
</script>
