// src/components/pages/Settings/Filter/FilterCapitalsSettings.tsx
import { useGuildSettingsChangesContext } from '@contexts/Settings/GuildSettingsChangesContext';
import { useGuildSettingsContext } from '@contexts/Settings/GuildSettingsContext';
import Section from '@layout/Settings/Section';
import { MenuItem, Typography } from '@material-ui/core';
import Slider from '@material-ui/core/Slider';
import SimpleGrid from '@mui/SimpleGrid';
import Select from '@selects/Select';
import SelectBoolean from '@selects/SelectBoolean';
import SelectDuration from '@selects/SelectDuration';
import { bitwiseHas, bitwiseSet, updateSliderValueObj } from '@utils/util';
import React, { FC, Fragment, memo } from 'react';

const FilterCapitalsSettings: FC = () => {
	const { guildSettings } = useGuildSettingsContext();
	const { setGuildSettingsChanges } = useGuildSettingsChangesContext();

	return (
		<Fragment>
			<Section title="Capital Letters Filter">
				<SimpleGrid>
					<SelectBoolean
						title={`Filter ${guildSettings.selfmod.capitals.enabled ? 'Enabled' : 'Disabled'}`}
						onChange={event => setGuildSettingsChanges({ selfmod: { capitals: { enabled: event.target.checked } } })}
						currentValue={guildSettings.selfmod.capitals.enabled}
						description="Whether or not this system should be enabled."
					/>
					<SelectBoolean
						title={`Alerts ${bitwiseHas(guildSettings.selfmod.capitals.softAction, 0b100) ? 'Enabled' : 'Disabled'}`}
						onChange={event =>
							setGuildSettingsChanges({
								selfmod: {
									capitals: {
										softAction: bitwiseSet(guildSettings.selfmod.capitals.softAction, 0b100, event.target.checked)
									}
								}
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmod.capitals.softAction, 0b100)}
						description="Toggle message alerts in the channel the infraction took place."
					/>
					<SelectBoolean
						title={`Logs ${bitwiseHas(guildSettings.selfmod.capitals.softAction, 0b010) ? 'Enabled' : 'Disabled'}`}
						onChange={event =>
							setGuildSettingsChanges({
								selfmod: {
									capitals: {
										softAction: bitwiseSet(guildSettings.selfmod.capitals.softAction, 0b010, event.target.checked)
									}
								}
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmod.capitals.softAction, 0b010)}
						description="Toggle message logs in the moderation logs channel."
					/>
					<SelectBoolean
						title={`Deletes ${bitwiseHas(guildSettings.selfmod.capitals.softAction, 0b001) ? 'Enabled' : 'Disabled'}`}
						onChange={event =>
							setGuildSettingsChanges({
								selfmod: {
									capitals: {
										softAction: bitwiseSet(guildSettings.selfmod.capitals.softAction, 0b001, event.target.checked)
									}
								}
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmod.capitals.softAction, 0b001)}
						description="Toggle message deletions."
					/>
				</SimpleGrid>
			</Section>
			<Section title="Punishments">
				<SimpleGrid direction="row" justify="flex-start">
					<Select
						title="Action"
						helperText="The action to perform as punishment"
						value={guildSettings.selfmod.capitals.hardAction}
						onChange={e => setGuildSettingsChanges({ selfmod: { capitals: { hardAction: e.target.value } } })}
					>
						<MenuItem value={0}>None</MenuItem>
						<MenuItem value={1}>Warning</MenuItem>
						<MenuItem value={2}>Kick</MenuItem>
						<MenuItem value={3}>Mute</MenuItem>
						<MenuItem value={4}>Softban</MenuItem>
						<MenuItem value={5}>Ban</MenuItem>
					</Select>
					<SelectDuration
						value={guildSettings.selfmod.capitals.hardActionDuration}
						min={1000}
						onChange={duration => setGuildSettingsChanges({ selfmod: { capitals: { hardActionDuration: duration } } })}
					></SelectDuration>
				</SimpleGrid>
				<Typography>Maximum Threshold</Typography>
				<Slider
					value={guildSettings.selfmod.capitals.thresholdMaximum}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('capitals', 'thresholdMaximum', value))}
					aria-labelledby="Capitals selfmod filter maximum threshold slider"
					valueLabelDisplay="auto"
					min={0}
					max={60}
				/>
				<Typography>Threshold Duration (in seconds)</Typography>
				<Slider
					value={guildSettings.selfmod.capitals.thresholdDuration / 1000}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('capitals', 'thresholdDuration', value, 1000))}
					aria-labelledby="Capitals selfmod filter threshold duration slider"
					valueLabelDisplay="auto"
					min={0}
					max={120}
				/>
			</Section>
			<Section title="Options">
				<Typography>Minimum Characters</Typography>
				<Slider
					value={guildSettings.selfmod.capitals.minimum}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('capitals', 'minimum', value))}
					aria-labelledby="Capitals selfmod filter minimum characters slider"
					valueLabelDisplay="auto"
					min={5}
					max={2000}
				/>
				<Typography>Maximum Uppercase Characters (%)</Typography>
				<Slider
					value={guildSettings.selfmod.capitals.maximum}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('capitals', 'maximum', value))}
					aria-labelledby="Capitals selfmod filter maximum uppercase characters slider"
					valueLabelDisplay="auto"
					min={10}
					max={100}
				/>
			</Section>
		</Fragment>
	);
};

export default memo(FilterCapitalsSettings);

// components/Settings/Filter/FilterCapitalsSettings.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useGuildSettingsChanges } from '@/composables/settings/useGuildSettingsChanges';
import { useGuildSettings } from '@/composables/settings/useGuildSettings';
import { bitwiseHas, bitwiseSet, removeNonAlphaNumeric, updateSliderValueObj } from '@/utils/util';

const { guildSettings } = useGuildSettings();
const { setGuildSettingsChanges } = useGuildSettingsChanges();

const newWord = ref('');

const addWord = () => {
	const word = removeNonAlphaNumeric(newWord.value).toLowerCase();
	if (word.length < 3 || guildSettings.value.selfmodFilterRaw.includes(word)) return;
	setGuildSettingsChanges({
		selfmodFilterRaw: [...guildSettings.value.selfmodFilterRaw, word]
	});
	newWord.value = '';
};

const removeWord = (wordToRemove: string) => {
	setGuildSettingsChanges({
		selfmodFilterRaw: guildSettings.value.selfmodFilterRaw.filter((word) => word !== wordToRemove)
	});
};

const updateSoftAction = (bit: number, checked: boolean) => {
	setGuildSettingsChanges({
		selfmodFilterSoftAction: bitwiseSet(guildSettings.value.selfmodFilterSoftAction, bit, checked)
	});
};

const thresholdMaximum = computed({
	get: () => guildSettings.value.selfmodFilterThresholdMaximum,
	set: (value) => setGuildSettingsChanges(updateSliderValueObj('selfmodFilterThresholdMaximum', value))
});

const thresholdDuration = computed({
	get: () => guildSettings.value.selfmodFilterThresholdDuration / 1000,
	set: (value) => setGuildSettingsChanges(updateSliderValueObj('selfmodFilterThresholdDuration', value, 1000))
});
</script>

<template>
	<div>
		<PresentationalLayoutsSettingsSection title="Word Filter">
			<div class="grid grid-cols-1 gap-4">
				<SelectsSelectBoolean
					:title="`Filter ${guildSettings.selfmodFilterEnabled ? 'Enabled' : 'Disabled'}`"
					@change="setGuildSettingsChanges({ selfmodFilterEnabled: $event })"
					:current-value="guildSettings.selfmodFilterEnabled"
					description="Whether or not this system should be enabled."
				/>
				<SelectsSelectBoolean
					:title="`Alerts ${bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b100) ? 'Enabled' : 'Disabled'}`"
					@change="updateSoftAction(0b100, $event)"
					:current-value="bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b100)"
					description="Toggle message alerts in the channel the infraction took place."
				/>
				<SelectsSelectBoolean
					:title="`Logs ${bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b010) ? 'Enabled' : 'Disabled'}`"
					@change="updateSoftAction(0b010, $event)"
					:current-value="bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b010)"
					description="Toggle message logs in the moderation logs channel."
				/>
				<SelectsSelectBoolean
					:title="`Deletes ${bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b001) ? 'Enabled' : 'Disabled'}`"
					@change="updateSoftAction(0b001, $event)"
					:current-value="bitwiseHas(guildSettings.selfmodFilterSoftAction, 0b001)"
					description="Toggle message deletions."
				/>
			</div>
		</PresentationalLayoutsSettingsSection>

		<PresentationalLayoutsSettingsSection title="Punishments">
			<div class="grid grid-cols-2 gap-4">
				<SelectsSelect
					title="Action"
					helper-text="The action to perform as punishment"
					:value="guildSettings.selfmodFilterHardAction"
					@change="setGuildSettingsChanges({ selfmodFilterHardAction: $event as number })"
				>
					<option :value="0">None</option>
					<option :value="1">Warning</option>
					<option :value="2">Kick</option>
					<option :value="3">Mute</option>
					<option :value="4">Softban</option>
					<option :value="5">Ban</option>
				</SelectsSelect>
				<SelectsSelectDuration
					:value="guildSettings.selfmodFilterHardActionDuration"
					:min="1000"
					@change="setGuildSettingsChanges({ selfmodFilterHardActionDuration: $event })"
				/>
			</div>

			<div class="mt-4">
				<p>Maximum Threshold</p>
				<input v-model="thresholdMaximum" type="range" min="0" max="60" class="w-full" />
			</div>

			<div class="mt-4">
				<p>Threshold Duration (in seconds)</p>
				<input v-model="thresholdDuration" type="range" min="0" max="120" class="w-full" />
			</div>
		</PresentationalLayoutsSettingsSection>

		<PresentationalLayoutsSettingsSection title="Filtered Words">
			<form @submit.prevent="addWord">
				<div class="mb-2 flex items-center">
					<input v-model="newWord" class="mb-1 mr-1" placeholder="Add Word" />
					<button type="submit" class="btn btn-primary">Confirm</button>
				</div>
			</form>

			<div v-if="guildSettings.selfmodFilterRaw.length !== 0" class="p-1">
				<span
					v-for="word in guildSettings.selfmodFilterRaw"
					:key="word"
					class="badge badge-primary m-1 cursor-pointer"
					@click="removeWord(word)"
				>
					{{ word }}
				</span>
			</div>
		</PresentationalLayoutsSettingsSection>
	</div>
</template>
