// src/components/pages/Settings/Filter/FilterReactionSettings.tsx
import { useGuildSettingsChangesContext } from '@contexts/Settings/GuildSettingsChangesContext';
import { useGuildSettingsContext } from '@contexts/Settings/GuildSettingsContext';
import Section from '@layout/Settings/Section';
import SimpleGrid from '@material/SimpleGrid';
import Select from '@selects/Select';
import SelectBoolean from '@selects/SelectBoolean';
import SelectDuration from '@selects/SelectDuration';
import { bitwiseHas, bitwiseSet, updateSliderValueObj } from '@utils/util';
import { Fragment, memo, type FC } from 'react';

import { MenuItem, Slider, Typography } from '@mui/material';

const FilterReactionSettings: FC = () => {
	const { guildSettings } = useGuildSettingsContext();
	const { setGuildSettingsChanges } = useGuildSettingsChangesContext();

	return (
		<Fragment>
			<Section title="Reaction Filter">
				<SimpleGrid>
					<SelectBoolean
						title={`Filter ${guildSettings.selfmodReactionsEnabled ? 'Enabled' : 'Disabled'}`}
						onChange={(event) => setGuildSettingsChanges({ selfmodReactionsEnabled: event.target.checked })}
						currentValue={guildSettings.selfmodReactionsEnabled}
						description="Whether or not this system should be enabled."
					/>
					<SelectBoolean
						title={`Alerts ${bitwiseHas(guildSettings.selfmodReactionsSoftAction, 0b100) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodReactionsSoftAction: bitwiseSet(guildSettings.selfmodReactionsSoftAction, 0b100, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodReactionsSoftAction, 0b100)}
						description="Toggle message alerts in the channel the infraction took place."
					/>
					<SelectBoolean
						title={`Logs ${bitwiseHas(guildSettings.selfmodReactionsSoftAction, 0b010) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodReactionsSoftAction: bitwiseSet(guildSettings.selfmodReactionsSoftAction, 0b010, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodReactionsSoftAction, 0b010)}
						description="Toggle message logs in the moderation logs channel."
					/>
					<SelectBoolean
						title={`Deletes ${bitwiseHas(guildSettings.selfmodReactionsSoftAction, 0b001) ? 'Enabled' : 'Disabled'}`}
						onChange={(event) =>
							setGuildSettingsChanges({
								selfmodReactionsSoftAction: bitwiseSet(guildSettings.selfmodReactionsSoftAction, 0b001, event.target.checked)
							})
						}
						currentValue={bitwiseHas(guildSettings.selfmodReactionsSoftAction, 0b001)}
						description="Toggle message deletions."
					/>
				</SimpleGrid>
			</Section>
			<Section title="Punishments">
				<SimpleGrid direction="row" justifyContent="flex-start">
					<Select
						title="Action"
						helperText="The action to perform as punishment"
						value={guildSettings.selfmodReactionsHardAction}
						onChange={(e) => setGuildSettingsChanges({ selfmodReactionsHardAction: e.target.value })}
					>
						<MenuItem value={0}>None</MenuItem>
						<MenuItem value={1}>Warning</MenuItem>
						<MenuItem value={2}>Kick</MenuItem>
						<MenuItem value={3}>Mute</MenuItem>
						<MenuItem value={4}>Softban</MenuItem>
						<MenuItem value={5}>Ban</MenuItem>
					</Select>
					<SelectDuration
						value={guildSettings.selfmodReactionsHardActionDuration}
						min={1000}
						onChange={(duration) => setGuildSettingsChanges({ selfmodReactionsHardActionDuration: duration })}
					></SelectDuration>
				</SimpleGrid>
				<Typography>Maximum Threshold</Typography>
				<Slider
					value={guildSettings.selfmodReactionsThresholdMaximum}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('selfmodReactionsThresholdMaximum', value))}
					aria-labelledby="Reactions selfmod filter maximum threshold slider"
					valueLabelDisplay="auto"
					min={0}
					max={60}
				/>
				<Typography>Threshold Duration (in seconds)</Typography>
				<Slider
					value={guildSettings.selfmodReactionsThresholdDuration / 1000}
					onChange={(_, value) => setGuildSettingsChanges(updateSliderValueObj('selfmodReactionsThresholdDuration', value, 1000))}
					aria-labelledby="Reactions selfmod filter threshold duration slider"
					valueLabelDisplay="auto"
					min={0}
					max={120}
				/>
			</Section>
		</Fragment>
	);
};

export default memo(FilterReactionSettings);

// components/Settings/Filter/FilterReactionSettings.vue
<script setup lang="ts">
import { useGuildSettings } from '~/composables/settings/useGuildSettings';
import { useGuildSettingsChanges } from '~/composables/settings/useGuildSettingsChanges';

const { guildSettings } = useGuildSettings();
const { setGuildSettingsChanges } = useGuildSettingsChanges();

const softActionEnabled = computed(() => ({
	alerts: bitwiseHas(guildSettings.value.selfmodReactionsSoftAction, 0b100),
	logs: bitwiseHas(guildSettings.value.selfmodReactionsSoftAction, 0b010),
	deletes: bitwiseHas(guildSettings.value.selfmodReactionsSoftAction, 0b001)
}));

const updateSoftAction = (bit: number, checked: boolean) => {
	setGuildSettingsChanges({
		selfmodReactionsSoftAction: bitwiseSet(guildSettings.value.selfmodReactionsSoftAction, bit, checked)
	});
};
</script>

<template>
	<div>
		<PresentationalLayoutsSettingsSection title="Reaction Filter">
			<div class="grid grid-cols-1 gap-4 md:grid-cols-2">
				<SelectsSelectBoolean
					:title="`Filter ${guildSettings.selfmodReactionsEnabled ? 'Enabled' : 'Disabled'}`"
					:current-value="guildSettings.selfmodReactionsEnabled"
					description="Whether or not this system should be enabled."
					@change="(value) => setGuildSettingsChanges({ selfmodReactionsEnabled: value })"
				/>
				<SelectsSelectBoolean
					:title="`Alerts ${softActionEnabled.alerts ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.alerts"
					description="Toggle message alerts in the channel the infraction took place."
					@change="(value) => updateSoftAction(0b100, value)"
				/>
				<SelectsSelectBoolean
					:title="`Logs ${softActionEnabled.logs ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.logs"
					description="Toggle message logs in the moderation logs channel."
					@change="(value) => updateSoftAction(0b010, value)"
				/>
				<SelectsSelectBoolean
					:title="`Deletes ${softActionEnabled.deletes ? 'Enabled' : 'Disabled'}`"
					:current-value="softActionEnabled.deletes"
					description="Toggle message deletions."
					@change="(value) => updateSoftAction(0b001, value)"
				/>
			</div>
		</PresentationalLayoutsSettingsSection>

		<PresentationalLayoutsSettingsSection title="Punishments">
			<div class="flex flex-col gap-4 md:flex-row">
				<SelectsSelect
					title="Action"
					helper-text="The action to perform as punishment"
					:value="guildSettings.selfmodReactionsHardAction"
					@change="(value) => value && setGuildSettingsChanges({ selfmodReactionsHardAction: typeof value === 'string' ? +value : value })"
				>
					<option :value="0">None</option>
					<option :value="1">Warning</option>
					<option :value="2">Kick</option>
					<option :value="3">Mute</option>
					<option :value="4">Softban</option>
					<option :value="5">Ban</option>
				</SelectsSelect>
				<SelectsSelectDuration
					:value="guildSettings.selfmodReactionsHardActionDuration"
					:min="1000"
					@change="(duration) => setGuildSettingsChanges({ selfmodReactionsHardActionDuration: duration })"
				/>
			</div>

			<div class="mt-4">
				<p>Maximum Threshold</p>
				<input
					type="range"
					min="0"
					max="60"
					:value="guildSettings.selfmodReactionsThresholdMaximum"
					class="range"
					@input="
						(e) =>
							setGuildSettingsChanges(
								updateSliderValueObj('selfmodReactionsThresholdMaximum', Number((e.target as HTMLInputElement).value))
							)
					"
				/>
			</div>

			<div class="mt-4">
				<p>Threshold Duration (in seconds)</p>
				<input
					type="range"
					min="0"
					max="120"
					:value="guildSettings.selfmodReactionsThresholdDuration / 1000"
					class="range"
					@input="
						(e) =>
							setGuildSettingsChanges(
								updateSliderValueObj('selfmodReactionsThresholdDuration', Number((e.target as HTMLInputElement).value) * 1000)
							)
					"
				/>
			</div>
		</PresentationalLayoutsSettingsSection>
	</div>
</template>
