// src/components/pages/Settings/EventSettings.tsx
import { ConfigurableMessageEvents, ConfigurableModerationEvents } from '@config/SettingsDataEntries';
import { useGuildSettingsChangesContext } from '@contexts/Settings/GuildSettingsChangesContext';
import { useGuildSettingsContext } from '@contexts/Settings/GuildSettingsContext';
import Section from '@layout/Settings/Section';
import SimpleGrid from '@material/SimpleGrid';
import { Typography } from '@mui/material';
import Link from '@routing/Link';
import SelectBoolean from '@selects/SelectBoolean';
import { useRouter } from 'next/router';
import { memo, type FC } from 'react';

const EventSettings: FC = () => {
	const router = useRouter();
	const { guildSettings } = useGuildSettingsContext();
	const { setGuildSettingsChanges } = useGuildSettingsChangesContext();

	const [guildId] = router.query.id;

	return (
		<>
			<Section title="Moderation Events">
				<Typography variant="subtitle2" color="textPrimary">
					These events involve moderation actions and require that you setup the Moderation Logs channel on{' '}
					<Link href={`/guilds/${guildId}/channels`}>the Channels page</Link>
				</Typography>
				<SimpleGrid>
					{ConfigurableModerationEvents.map(({ title, key, description }, index) => (
						<SelectBoolean
							key={index}
							title={title}
							description={description}
							currentValue={guildSettings[key]}
							onChange={(event) => setGuildSettingsChanges({ [key]: event.target.checked })}
						/>
					))}
				</SimpleGrid>
			</Section>

			<Section title="Message Events">
				<Typography variant="subtitle2" color="textPrimary">
					These events involve message events, the channels to set up vary on the type of event and each channel can be configured on{' '}
					<Link href={`/guilds/${guildId}/channels`}>the Channels page</Link>
				</Typography>
				<SimpleGrid>
					{ConfigurableMessageEvents.map(({ title, key, description }, index) => (
						<SelectBoolean
							key={index}
							title={title}
							description={description}
							currentValue={guildSettings[key]}
							onChange={(event) => setGuildSettingsChanges({ [key]: event.target.checked })}
						/>
					))}
				</SimpleGrid>
			</Section>
		</>
	);
};

export default memo(EventSettings);

// components/pages/Settings/event-settings.vue
<script setup lang="ts">
import { useRouter } from 'vue-router';
import { useGuildSettings } from '~/composables/settings/useGuildSettings';
import { ConfigurableModerationEvents, ConfigurableMessageEvents } from '~/config/SettingsDataEntries';
import Section from '~/layouts/settings/section.vue';
import SelectBoolean from '~/components/selects/SelectBoolean.vue';
import { useGuildSettingsChanges } from '~/composables/settings/useGuildSettingsChanges';

const router = useRouter();
const { guildSettings } = useGuildSettings();
const { setGuildSettingsChanges } = useGuildSettingsChanges();

const guildId = computed(() => router.currentRoute.value.params.id as string);
</script>

<template>
	<div>
		<Section title="Moderation Events">
			<p class="mb-4 text-sm">
				These events involve moderation actions and require that you setup the Moderation Logs channel on
				<NuxtLink :to="`/guilds/${guildId}/channels`" class="link">the Channels page</NuxtLink>
			</p>
			<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
				<SelectBoolean
					v-for="{ title, key, description } in ConfigurableModerationEvents"
					:key="key"
					:title="title"
					:description="description"
					:current-value="guildSettings[key]"
					@change="(value) => setGuildSettingsChanges({ [key]: value })"
				/>
			</div>
		</Section>

		<Section title="Message Events">
			<p class="mb-4 text-sm">
				These events involve message events, the channels to set up vary on the type of event and each channel can be configured on
				<NuxtLink :to="`/guilds/${guildId}/channels`" class="link">the Channels page</NuxtLink>
			</p>
			<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
				<SelectBoolean
					v-for="{ title, key, description } in ConfigurableMessageEvents"
					:key="key"
					:title="title"
					:description="description"
					:current-value="guildSettings[key]"
					@change="(value) => setGuildSettingsChanges({ [key]: value })"
				/>
			</div>
		</Section>
	</div>
</template>
