// src/components/pages/Settings/ModerationSettings.tsx
import { ConfigurableModerationKeys } from '#config/SettingsDataEntries';
import { useGuildSettingsChangesContext } from '#contexts/Settings/GuildSettingsChangesContext';
import { useGuildSettingsContext } from '#contexts/Settings/GuildSettingsContext';
import Section from '#layout/Settings/Section';
import SimpleGrid from '#mui/SimpleGrid';
import SelectBoolean from '#selects/SelectBoolean';
import React, { FC, memo } from 'react';

const ModerationSettings: FC = () => {
	const { guildSettings } = useGuildSettingsContext();
	const { setGuildSettingsChanges } = useGuildSettingsChangesContext();

	return (
		<Section title="Punishment Settings">
			<p>These settings affect what Skyra does when you're punishing (ban, kick, mute, etc) someone.</p>
			<SimpleGrid>
				{ConfigurableModerationKeys.map(({ description, key, name }, index) => (
					<SelectBoolean
						key={index}
						title={name}
						currentValue={guildSettings[key]}
						description={description}
						onChange={(event) =>
							setGuildSettingsChanges({
								[key]: event.target.checked
							})
						}
					/>
				))}
			</SimpleGrid>
		</Section>
	);
};

export default memo(ModerationSettings);

// components/pages/Settings/moderation-settings.vue
<script setup lang="ts">
import { useGuildSettings } from '~/composables/settings/useGuildSettings';
import { useGuildSettingsChanges } from '~/composables/settings/useGuildSettingsChanges';
import { ConfigurableModerationKeys } from '~/config/SettingsDataEntries';
import Section from '~/layouts/settings/section.vue';
import SelectBoolean from '~/components/selects/SelectBoolean.vue';

const { guildSettings } = useGuildSettings();
const { setGuildSettingsChanges } = useGuildSettingsChanges();
</script>

<template>
	<Section title="Punishment Settings">
		<p>These settings affect what Skyra does when you're punishing (ban, kick, mute, etc) someone.</p>
		<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
			<SelectBoolean
				v-for="{ description, key, name } in ConfigurableModerationKeys"
				:key="key"
				:title="name"
				:current-value="guildSettings[key]"
				:description="description"
				@change="(value) => setGuildSettingsChanges({ [key]: value })"
			/>
		</div>
	</Section>
</template>
