// components/presentational/guild-card.vue
<template>
	<Link :href="guild.wolfstarIsIn ? `/guilds/${guild.id}` : guildAddURL(guild.id)" class="link">
		<div
			class="card m-2 cursor-pointer bg-secondary"
			:style="{
				minWidth: '230px',
				maxWidth: isMobile ? '90vw' : '230px',
				width: isMobile ? '90vw' : 'inherit',
				minHeight: '80px',
				maxHeight: '80px'
			}"
		>
			<div class="card-header flex items-center">
				<GuildIcon :guild="guild" />
				<div class="ml-2">
					<h3 class="card-title">{{ guild.name }}</h3>
					<p v-if="!guild.wolfstarIsIn" class="card-subtitle">Click to invite WolfStar</p>
				</div>
			</div>
		</div>
	</Link>
</template>

<script setup lang="ts">
import { computed, defineProps } from 'vue';
import Link from '~/components/routing/Link.vue';
import GuildIcon from './guild-icon.vue';
import { guildAddURL } from '~/composables/auth';
import type { ValuesType } from 'utility-types';
import type { TransformedLoginData } from '~/config/types/ApiData';
interface GuildCardProps {
	guild: ValuesType<NonNullable<TransformedLoginData['transformedGuilds']>>;
}

const props = defineProps<GuildCardProps>();

const isMobile = computed(() => window.innerWidth <= 768);
</script>

<style scoped>
.card {
	background-color: var(--secondary-main);
}
.card-header {
	display: flex;
	align-items: center;
}
.card-title {
	font-weight: 600;
	font-size: 1.25rem;
}
.card-subtitle {
	color: var(--text-secondary);
	font-size: 0.875rem;
}
</style>

// src/components/presentational/GuildCard.tsx
import type { TransformedLoginData } from '@config/types/ApiData';
import Link from '@routing/Link';
import { guildAddURL } from '@utils/constants';
import { cloneElement, memo } from 'react';
import type { ValuesType } from 'utility-types';
import styles from './GuildCard.module.css';
import GuildIcon from './GuildIcon';

import { Card, CardHeader } from '@mui/material';

interface GuildCardProps {
	guild: ValuesType<NonNullable<TransformedLoginData['transformedGuilds']>>;
}

const GuildCard = memo<GuildCardProps>(({ guild }) => (
	<Link href={guild.skyraIsIn ? `/guilds/${guild.id}` : guildAddURL(guild.id)} className={styles.link}>
		<Card
			elevation={2}
			sx={{
				minWidth: 230,
				maxWidth: {
					md: 230,
					xs: '90vw'
				},
				width: {
					md: 'inherit',
					xs: '90vw'
				},
				minHeight: 80,
				maxHeight: 80,
				bgcolor: 'secondary.main',
				m: 2,
				'&:hover': {
					cursor: 'pointer'
				}
			}}
		>
			<CardHeader
				classes={{ root: styles.headerRoot, content: styles.headerContent }}
				subheader={!guild.skyraIsIn && 'Click to invite Skyra'}
				avatar={<GuildIcon guild={guild} />}
				title={guild.name}
			/>
		</Card>
	</Link>
));

export const FilteredGuildCards = (pack?: TransformedLoginData) =>
	(pack?.transformedGuilds ?? [])
		// Filter on manageable servers
		.filter((g) => g.manageable)
		// Sort by whether Skyra is in the server or not, or sort by the name of the server
		.sort((gA, gB) => (gA.skyraIsIn === gB.skyraIsIn ? gA.name.localeCompare(gB.name, 'en', { sensitivity: 'base' }) : gA.skyraIsIn ? -1 : 1))
		.map((g, index) => cloneElement(<GuildCard guild={g} key={index} />));
