// src/components/presentational/CommandsPage/Chips.tsx
import DiscordIcon from '@assets/DiscordIcon';
import type { FlattenedCommand } from '@config/types/ApiData';
import DoubleArrowIcon from '@mui/icons-material/DoubleArrow';
import LockIcon from '@mui/icons-material/Lock';
import { Chip, Grid } from '@mui/material';
import { amber, deepOrange } from '@mui/material/colors';
import { useMobileContext } from 'contexts/MobileContext';
import { FC, memo, useCallback, useMemo } from 'react';

interface ChipsProps {
	command: FlattenedCommand;
}

const GuildOnlyPreconditions = ['Administrator', 'DJ', 'GuildOnly', 'Moderator', 'NewsOnly', 'NSFW', 'TextOnly'];

const Chips: FC<ChipsProps> = ({ command }) => {
	const { isMobile } = useMobileContext();

	const titles = useMemo<Record<number, string>>(
		() => ({
			4: 'This can only be ran by staff members.',
			5: 'This can only be ran by moderators and administrators.',
			6: 'This can only be ran by administrators.'
		}),
		[]
	);

	const mobileTitles = useMemo<Record<number, string>>(
		() => ({
			4: 'Staff members only',
			5: 'Moderators & administrators only',
			6: 'Administrators only'
		}),
		[]
	);

	const isGuildOnly = useCallback(() => {
		return command.preconditions.entries
			.flatMap((preconditionEntry) => preconditionEntry.entries)
			.filter(Boolean)
			.map((entry) => entry.name)
			.some((predicate) => GuildOnlyPreconditions.includes(predicate));
	}, [command.preconditions.entries]);

	return (
		<Grid container spacing={1} direction="row" alignContent="center" alignItems="center" justifyContent="flex-start">
			{command.permissionLevel > 0 && (
				<Grid item xs={12} md={5} lg={4}>
					<Chip
						size="small"
						label={isMobile ? mobileTitles[command.permissionLevel] : titles[command.permissionLevel]}
						icon={<DoubleArrowIcon />}
						color="secondary"
						sx={{
							p: 0.2,
							ml: 1,
							width: '100%',
							'& .MuiChip-iconSmall': {
								transform: 'rotate(-90deg)',
								color: amber[500]
							}
						}}
					/>
				</Grid>
			)}
			{isGuildOnly() && (
				<Grid item xs={12} md={5} lg={4}>
					<Chip
						size="small"
						label={isMobile ? 'Usable in servers only.' : 'This can only be used in servers.'}
						icon={<DiscordIcon />}
						color="secondary"
						sx={{
							p: 0.2,
							ml: 1,
							width: '100%'
						}}
					/>
				</Grid>
			)}
			{command.guarded && (
				<Grid item xs={12} md={5} lg={4}>
					<Chip
						size="small"
						label="This command cannot be disabled."
						color="secondary"
						icon={<LockIcon />}
						sx={{
							p: 0.2,
							ml: 1,
							width: '100%',
							'& .MuiChip-iconSmall': {
								color: deepOrange[500]
							}
						}}
					/>
				</Grid>
			)}
		</Grid>
	);
};

export default memo(Chips);

// components/commands/chips.vue
<template>
	<div class="grid grid-cols-1 gap-2 md:grid-cols-2 lg:grid-cols-3">
		<CommandsChip v-if="command.permissionLevel > 0" :text="permissionText" icon="arrow-expand-down" />

		<CommandsChip v-if="isGuildOnly" :text="guildOnlyText" icon="discord" />

		<CommandsChip v-if="command.guarded" text="This command cannot be disabled" icon="lock" />
	</div>
</template>

<script setup lang="ts">
import type { FlattenedCommand } from '~/utils/types/ApiData';

interface CommandProps {
	command: FlattenedCommand;
}

const props = defineProps<CommandProps>();
const { isMobile } = useDevice();

const PERMISSION_TITLES = {
	desktop: {
		4: 'This can only be ran by staff members.',
		5: 'This can only be ran by moderators and administrators.',
		6: 'This can only be ran by administrators.'
	},
	mobile: {
		4: 'Staff members only',
		5: 'Moderators & administrators only',
		6: 'Administrators only'
	}
} as const;

const GUILD_PRECONDITIONS = ['Administrator', 'DJ', 'GuildOnly', 'Moderator', 'NewsOnly', 'NSFW', 'TextOnly'] as const;

const permissionText = computed(() => {
	const titles = isMobile ? PERMISSION_TITLES.mobile : PERMISSION_TITLES.desktop;
	return titles[props.command.permissionLevel as keyof typeof titles] ?? '';
});

const guildOnlyText = computed(() => (isMobile ? 'Usable in servers only.' : 'This can only be used in servers.'));

const isGuildOnly = computed(() =>
	props.command.preconditions.entries
		.flatMap((entry) => entry.entries)
		.filter(Boolean)
		.map((entry) => entry.name)
		.some((name) => GUILD_PRECONDITIONS.includes(name as (typeof GUILD_PRECONDITIONS)[number]))
);
</script>

<style scoped>
.chip {
	@apply flex items-center justify-between rounded-lg bg-primary p-2 px-4 text-white;
}

.chip.secondary {
	@apply bg-secondary;
}
</style>
